
// Dữ liệu Từ vựng HSK 1 (Đầy đủ 150/150 từ) và HSK 2 (Đầy đủ 150/150 từ)
const hskData = {
    "1": [
        { word: "爱", pinyin: "ài", meaning: "yêu, thích" },
        { word: "八", pinyin: "bā", meaning: "tám" },
        { word: "爸爸", pinyin: "bàba", meaning: "bố, ba" },
        { word: "杯子", pinyin: "bēizi", meaning: "cốc, ly" },
        { word: "北京", pinyin: "Běijīng", meaning: "Bắc Kinh" },
        { word: "本", pinyin: "běn", meaning: "quyển, cuốn" },
        { word: "不客气", pinyin: "bú kèqi", meaning: "đừng khách sáo, không có gì" },
        { word: "不", pinyin: "bù", meaning: "không" },
        { word: "菜", pinyin: "cài", meaning: "rau, món ăn" },
        { word: "茶", pinyin: "chá", meaning: "trà" },
        { word: "吃", pinyin: "chī", meaning: "ăn" },
        { word: "出租车", pinyin: "chūzūchē", meaning: "xe taxi" },
        { word: "打电话", pinyin: "dǎ diànhuà", meaning: "gọi điện thoại" },
        { word: "大", pinyin: "dà", meaning: "to, lớn" },
        { word: "的", pinyin: "de", meaning: "của (trợ từ)" },
        { word: "点", pinyin: "diǎn", meaning: "giờ, chút" },
        { word: "电脑", pinyin: "diànnǎo", meaning: "máy tính" },
        { word: "电视", pinyin: "diànshì", meaning: "tivi" },
        { word: "电影", pinyin: "diànyǐng", meaning: "phim ảnh" },
        { word: "东西", pinyin: "dōngxi", meaning: "đồ vật, đồ đạc" },
        { word: "都", pinyin: "dōu", meaning: "đều" },
        { word: "读", pinyin: "dú", meaning: "đọc" },
        { word: "对不起", pinyin: "duìbuqǐ", meaning: "xin lỗi" },
        { word: "多", pinyin: "duō", meaning: "nhiều" },
        { word: "多少", pinyin: "duōshao", meaning: "bao nhiêu" },
        { word: "儿子", pinyin: "érzi", meaning: "con trai" },
        { word: "二", pinyin: "èr", meaning: "hai" },
        { word: "饭馆", pinyin: "fànguǎn", meaning: "nhà hàng, quán ăn" },
        { word: "飞机", pinyin: "fēijī", meaning: "máy bay" },
        { word: "分钟", pinyin: "fēnzhōng", meaning: "phút" },
        { word: "高兴", pinyin: "gāoxìng", meaning: "vui vẻ, mừng" },
        { word: "个", pinyin: "gè", meaning: "cái, con (lượng từ)" },
        { word: "工作", pinyin: "gōngzuò", meaning: "công việc, làm việc" },
        { word: "汉语", pinyin: "Hànyǔ", meaning: "tiếng Hán" },
        { word: "好", pinyin: "hǎo", meaning: "tốt, khỏe, hay" },
        { word: "号", pinyin: "hào", meaning: "ngày, số" },
        { word: "喝", pinyin: "hē", meaning: "uống" },
        { word: "和", pinyin: "hé", meaning: "và, với" },
        { word: "很", pinyin: "hěn", meaning: "rất" },
        { word: "后面", pinyin: "hòumiàn", meaning: "phía sau" },
        { word: "回", pinyin: "huí", meaning: "về, trở về" },
        { word: "会", pinyin: "huì", meaning: "biết, sẽ" },
        { word: "几", pinyin: "jǐ", meaning: "mấy" },
        { word: "家", pinyin: "jiā", meaning: "nhà, gia đình" },
        { word: "叫", pinyin: "jiào", meaning: "gọi, tên là" },
        { word: "今天", pinyin: "jīntiān", meaning: "hôm nay" },
        { word: "九", pinyin: "jiǔ", meaning: "chín" },
        { word: "开", pinyin: "kāi", meaning: "mở, lái (xe)" },
        { word: "看", pinyin: "kàn", meaning: "nhìn, xem, đọc" },
        { word: "看见", pinyin: "kànjiàn", meaning: "nhìn thấy" },
        { word: "块", pinyin: "kuài", meaning: "đồng (tiền), miếng" },
        { word: "来", pinyin: "lái", meaning: "đến, tới" },
        { word: "老师", pinyin: "lǎoshī", meaning: "giáo viên, thầy cô" },
        { word: "了", pinyin: "le", meaning: "rồi (trợ từ)" },
        { word: "冷", pinyin: "lěng", meaning: "lạnh" },
        { word: "里", pinyin: "lǐ", meaning: "trong, bên trong" },
        { word: "零", pinyin: "líng", meaning: "số 0" },
        { word: "六", pinyin: "liù", meaning: "sáu" },
        { word: "妈妈", pinyin: "māma", meaning: "mẹ" },
        { word: "吗", pinyin: "ma", meaning: "không (trợ từ nghi vấn)" },
        { word: "买", pinyin: "mǎi", meaning: "mua" },
        { word: "猫", pinyin: "māo", meaning: "con mèo" },
        { word: "没关系", pinyin: "méi guānxi", meaning: "không sao" },
        { word: "没有", pinyin: "méiyǒu", meaning: "không có" },
        { word: "米饭", pinyin: "mǐfàn", meaning: "cơm" },
        { word: "明天", pinyin: "míngtiān", meaning: "ngày mai" },
        { word: "名字", pinyin: "míngzi", meaning: "tên" },
        { word: "哪", pinyin: "nǎ", meaning: "nào" },
        { word: "哪儿", pinyin: "nǎr", meaning: "ở đâu" },
        { word: "那", pinyin: "nà", meaning: "kia, đó" },
        { word: "那儿", pinyin: "nàr", meaning: "chỗ kia, nơi đó" },
        { word: "呢", pinyin: "ne", meaning: "nhỉ, nhé (trợ từ)" },
        { word: "能", pinyin: "néng", meaning: "có thể" },
        { word: "你", pinyin: "nǐ", meaning: "bạn, anh, chị" },
        { word: "年", pinyin: "nián", meaning: "năm" },
        { word: "女儿", pinyin: "nǚ'ér", meaning: "con gái" },
        { word: "朋友", pinyin: "péngyou", meaning: "bạn bè" },
        { word: "漂亮", pinyin: "piàoliang", meaning: "đẹp" },
        { word: "苹果", pinyin: "píngguǒ", meaning: "quả táo" },
        { word: "七", pinyin: "qī", meaning: "bảy" },
        { word: "钱", pinyin: "qián", meaning: "tiền" },
        { word: "前面", pinyin: "qiánmiàn", meaning: "phía trước" },
        { word: "请", pinyin: "qǐng", meaning: "mời, xin" },
        { word: "去", pinyin: "qù", meaning: "đi" },
        { word: "热", pinyin: "rè", meaning: "nóng" },
        { word: "人", pinyin: "rén", meaning: "người" },
        { word: "认识", pinyin: "rènshi", meaning: "quen biết" },
        { word: "三", pinyin: "sān", meaning: "ba" },
        { word: "商店", pinyin: "shāngdiàn", meaning: "cửa hàng" },
        { word: "上", pinyin: "shàng", meaning: "trên, lên" },
        { word: "上午", pinyin: "shàngwǔ", meaning: "buổi sáng" },
        { word: "少", pinyin: "shǎo", meaning: "ít" },
        { word: "谁", pinyin: "shéi", meaning: "ai" },
        { word: "什么", pinyin: "shénme", meaning: "cái gì" },
        { word: "十", pinyin: "shí", meaning: "mười" },
        { word: "时候", pinyin: "shíhou", meaning: "lúc, khi" },
        { word: "是", pinyin: "shì", meaning: "là" },
        { word: "书", pinyin: "shū", meaning: "sách" },
        { word: "水", pinyin: "shuǐ", meaning: "nước" },
        { word: "水果", pinyin: "shuǐguǒ", meaning: "hoa quả, trái cây" },
        { word: "睡觉", pinyin: "shuìjiào", meaning: "ngủ" },
        { word: "说话", pinyin: "shuōhuà", meaning: "nói chuyện" },
        { word: "四", pinyin: "sì", meaning: "bốn" },
        { word: "岁", pinyin: "suì", meaning: "tuổi" },
        { word: "他", pinyin: "tā", meaning: "anh ấy" },
        { word: "她", pinyin: "tā", meaning: "cô ấy" },
        { word: "太", pinyin: "tài", meaning: "quá, lắm" },
        { word: "天气", pinyin: "tiānqì", meaning: "thời tiết" },
        { word: "听", pinyin: "tīng", meaning: "nghe" },
        { word: "同学", pinyin: "tóngxué", meaning: "bạn học" },
        { word: "喂", pinyin: "wèi", meaning: "alo, này" },
        { word: "我", pinyin: "wǒ", meaning: "tôi" },
        { word: "我们", pinyin: "wǒmen", meaning: "chúng tôi" },
        { word: "五", pinyin: "wǔ", meaning: "năm" },
        { word: "喜欢", pinyin: "xǐhuan", meaning: "thích" },
        { word: "下", pinyin: "xià", meaning: "dưới, xuống" },
        { word: "下午", pinyin: "xiàwǔ", meaning: "buổi chiều" },
        { word: "下雨", pinyin: "xiàyǔ", meaning: "trời mưa" },
        { word: "先生", pinyin: "xiānsheng", meaning: "ông, tiên sinh, ngài" },
        { word: "现在", pinyin: "xiànzài", meaning: "bây giờ" },
        { word: "想", pinyin: "xiǎng", meaning: "nhớ, muốn, nghĩ" },
        { word: "小", pinyin: "xiǎo", meaning: "nhỏ, bé" },
        { word: "小姐", pinyin: "xiǎojiě", meaning: "cô, tiểu thư" },
        { word: "些", pinyin: "xiē", meaning: "một vài, một ít" },
        { word: "写", pinyin: "xiě", meaning: "viết" },
        { word: "谢谢", pinyin: "xièxie", meaning: "cảm ơn" },
        { word: "星期", pinyin: "xīngqī", meaning: "tuần, thứ" },
        { word: "学生", pinyin: "xuésheng", meaning: "học sinh" },
        { word: "学习", pinyin: "xuéxí", meaning: "học tập" },
        { word: "学校", pinyin: "xuéxiào", meaning: "trường học" },
        { word: "一", pinyin: "yī", meaning: "một" },
        { word: "衣服", pinyin: "yīfu", meaning: "quần áo" },
        { word: "医生", pinyin: "yīshēng", meaning: "bác sĩ" },
        { word: "医院", pinyin: "yīyuàn", meaning: "bệnh viện" },
        { word: "椅子", pinyin: "yǐzi", meaning: "cái ghế" },
        { word: "有", pinyin: "yǒu", meaning: "có" },
        { word: "月", pinyin: "yuè", meaning: "tháng" },
        { word: "再见", pinyin: "zàijiàn", meaning: "tạm biệt" },
        { word: "在", pinyin: "zài", meaning: "ở, đang" },
        { word: "怎么", pinyin: "zěnme", meaning: "thế nào, làm sao" },
        { word: "怎么样", pinyin: "zěnmeyàng", meaning: "như thế nào" },
        { word: "这", pinyin: "zhè", meaning: "đây, này" },
        { word: "这儿", pinyin: "zhèr", meaning: "ở đây" },
        { word: "中国", pinyin: "Zhōngguó", meaning: "Trung Quốc" },
        { word: "中午", pinyin: "zhōngwǔ", meaning: "buổi trưa" },
        { word: "住", pinyin: "zhù", meaning: "sống, ở" },
        { word: "桌子", pinyin: "zhuōzi", meaning: "cái bàn" },
        { word: "字", pinyin: "zì", meaning: "chữ" },
        { word: "昨天", pinyin: "zuótiān", meaning: "hôm qua" },
        { word: "坐", pinyin: "zuò", meaning: "ngồi" },
        { word: "做", pinyin: "zuò", meaning: "làm" }
    ],
    "2": [
        { word: "吧", pinyin: "ba", meaning: "nhé, đi (trợ từ)" },
        { word: "白", pinyin: "bái", meaning: "trắng" },
        { word: "百", pinyin: "bǎi", meaning: "trăm" },
        { word: "帮助", pinyin: "bāngzhù", meaning: "giúp đỡ" },
        { word: "报纸", pinyin: "bàozhǐ", meaning: "tờ báo" },
        { word: "比", pinyin: "bǐ", meaning: "so với" },
        { word: "别", pinyin: "bié", meaning: "đừng" },
        { word: "长", pinyin: "cháng", meaning: "dài" },
        { word: "唱歌", pinyin: "chànggē", meaning: "hát" },
        { word: "出", pinyin: "chū", meaning: "ra, ra ngoài" },
        { word: "穿", pinyin: "chuān", meaning: "mặc, đi (giày)" },
        { word: "次", pinyin: "cì", meaning: "lần" },
        { word: "从", pinyin: "cóng", meaning: "từ" },
        { word: "错", pinyin: "cuò", meaning: "sai" },
        { word: "打篮球", pinyin: "dǎ lánqiú", meaning: "chơi bóng rổ" },
        { word: "大家", pinyin: "dàjiā", meaning: "mọi người" },
        { word: "到", pinyin: "dào", meaning: "đến" },
        { word: "得", pinyin: "de", meaning: "trợ từ mức độ" },
        { word: "等", pinyin: "děng", meaning: "chờ, đợi" },
        { word: "弟弟", pinyin: "dìdi", meaning: "em trai" },
        { word: "第一", pinyin: "dì-yī", meaning: "thứ nhất" },
        { word: "懂", pinyin: "dǒng", meaning: "hiểu" },
        { word: "对", pinyin: "duì", meaning: "đúng, đối với" },
        { word: "房间", pinyin: "fángjiān", meaning: "căn phòng" },
        { word: "非常", pinyin: "fēicháng", meaning: "vô cùng, rất" },
        { word: "服务员", pinyin: "fúwùyuán", meaning: "phục vụ, bồi bàn" },
        { word: "高", pinyin: "gāo", meaning: "cao" },
        { word: "告诉", pinyin: "gàosu", meaning: "nói cho biết, bảo" },
        { word: "哥哥", pinyin: "gēge", meaning: "anh trai" },
        { word: "给", pinyin: "gěi", meaning: "cho, đưa cho" },
        { word: "公共汽车", pinyin: "gōnggòng qìchē", meaning: "xe buýt" },
        { word: "公斤", pinyin: "gōngjīn", meaning: "kilôgam" },
        { word: "公司", pinyin: "gōngsī", meaning: "công ty" },
        { word: "狗", pinyin: "gǒu", meaning: "con chó" },
        { word: "贵", pinyin: "guì", meaning: "đắt" },
        { word: "过", pinyin: "guò", meaning: "qua, đã từng" },
        { word: "还", pinyin: "hái", meaning: "còn, vẫn" },
        { word: "孩子", pinyin: "háizi", meaning: "trẻ em, con" },
        { word: "黑", pinyin: "hēi", meaning: "đen" },
        { word: "红", pinyin: "hóng", meaning: "đỏ" },
        { word: "欢迎", pinyin: "huānyíng", meaning: "hoan nghênh, chào mừng" },
        { word: "回答", pinyin: "huídá", meaning: "trả lời" },
        { word: "机场", pinyin: "jīchǎng", meaning: "sân bay" },
        { word: "鸡蛋", pinyin: "jīdàn", meaning: "trứng gà" },
        { word: "件", pinyin: "jiàn", meaning: "chiếc, cái (áo, việc)" },
        { word: "教室", pinyin: "jiàoshì", meaning: "phòng học" },
        { word: "姐姐", pinyin: "jiějie", meaning: "chị gái" },
        { word: "介绍", pinyin: "jièshào", meaning: "giới thiệu" },
        { word: "进", pinyin: "jìn", meaning: "vào" },
        { word: "近", pinyin: "jìn", meaning: "gần" },
        { word: "就", pinyin: "jiù", meaning: "thì, ngay" },
        { word: "觉得", pinyin: "juéde", meaning: "cảm thấy" },
        { word: "咖啡", pinyin: "kāfēi", meaning: "cà phê" },
        { word: "开始", pinyin: "kāishǐ", meaning: "bắt đầu" },
        { word: "考试", pinyin: "kǎoshì", meaning: "kỳ thi, thi" },
        { word: "可能", pinyin: "kěnéng", meaning: "có thể" },
        { word: "可以", pinyin: "kěyǐ", meaning: "có thể, được" },
        { word: "课", pinyin: "kè", meaning: "bài học, tiết học" },
        { word: "快", pinyin: "kuài", meaning: "nhanh" },
        { word: "快乐", pinyin: "kuàilè", meaning: "vui vẻ" },
        { word: "累", pinyin: "lèi", meaning: "mệt" },
        { word: "离", pinyin: "lí", meaning: "cách (khoảng cách)" },
        { word: "两", pinyin: "liǎng", meaning: "hai (lượng từ)" },
        { word: "路", pinyin: "lù", meaning: "đường" },
        { word: "旅游", pinyin: "lǚyóu", meaning: "du lịch" },
        { word: "卖", pinyin: "mài", meaning: "bán" },
        { word: "慢", pinyin: "màn", meaning: "chậm" },
        { word: "忙", pinyin: "máng", meaning: "bận" },
        { word: "每", pinyin: "měi", meaning: "mỗi" },
        { word: "妹妹", pinyin: "mèimei", meaning: "em gái" },
        { word: "门", pinyin: "mén", meaning: "cửa" },
        { word: "男", pinyin: "nán", meaning: "nam, đàn ông" },
        { word: "您", pinyin: "nín", meaning: "ngài, ông/bà (kính ngữ)" },
        { word: "牛奶", pinyin: "niúnǎi", meaning: "sữa bò" },
        { word: "女", pinyin: "nǚ", meaning: "nữ, phụ nữ" },
        { word: "旁边", pinyin: "pángbiān", meaning: "bên cạnh" },
        { word: "跑步", pinyin: "pǎobù", meaning: "chạy bộ" },
        { word: "便宜", pinyin: "piányi", meaning: "rẻ" },
        { word: "票", pinyin: "piào", meaning: "vé" },
        { word: "妻子", pinyin: "qīzi", meaning: "vợ" },
        { word: "起床", pinyin: "qǐchuáng", meaning: "thức dậy" },
        { word: "千", pinyin: "qiān", meaning: "nghìn" },
        { word: "铅笔", pinyin: "qiānbǐ", meaning: "bút chì" },
        { word: "晴", pinyin: "qíng", meaning: "nắng, trời quang" },
        { word: "去年", pinyin: "qùnián", meaning: "năm ngoái" },
        { word: "让", pinyin: "ràng", meaning: "nhường, cho phép, bảo" },
        { word: "日", pinyin: "rì", meaning: "ngày" },
        { word: "上班", pinyin: "shàngbān", meaning: "đi làm" },
        { word: "身体", pinyin: "shēntǐ", meaning: "thân thể, sức khỏe" },
        { word: "生病", pinyin: "shēngbìng", meaning: "bị bệnh" },
        { word: "生日", pinyin: "shēngrì", meaning: "sinh nhật" },
        { word: "时间", pinyin: "shíjiān", meaning: "thời gian" },
        { word: "事情", pinyin: "shìqing", meaning: "sự việc, công việc" },
        { word: "手表", pinyin: "shǒubiǎo", meaning: "đồng hồ đeo tay" },
        { word: "手机", pinyin: "shǒujī", meaning: "điện thoại di động" },
        { word: "送", pinyin: "sòng", meaning: "tặng, tiễn" },
        { word: "它", pinyin: "tā", meaning: "nó (vật, con vật)" },
        { word: "踢足球", pinyin: "tī zúqiú", meaning: "đá bóng" },
        { word: "题", pinyin: "tí", meaning: "câu hỏi, đề thi" },
        { word: "跳舞", pinyin: "tiàowǔ", meaning: "nhảy múa" },
        { word: "外", pinyin: "wài", meaning: "ngoài" },
        { word: "完", pinyin: "wán", meaning: "xong, hết" },
        { word: "玩", pinyin: "wán", meaning: "chơi" },
        { word: "晚上", pinyin: "wǎnshang", meaning: "buổi tối" },
        { word: "往", pinyin: "wǎng", meaning: "về phía, hướng về" },
        { word: "为什么", pinyin: "wèishénme", meaning: "tại sao" },
        { word: "问", pinyin: "wèn", meaning: "hỏi" },
        { word: "问题", pinyin: "wèntí", meaning: "câu hỏi, vấn đề" },
        { word: "西瓜", pinyin: "xīguā", meaning: "dưa hấu" },
        { word: "希望", pinyin: "xīwàng", meaning: "hy vọng" },
        { word: "洗", pinyin: "xǐ", meaning: "rửa, giặt" },
        { word: "小时", pinyin: "xiǎoshí", meaning: "tiếng, giờ đồng hồ" },
        { word: "笑", pinyin: "xiào", meaning: "cười" },
        { word: "新", pinyin: "xīn", meaning: "mới" },
        { word: "姓", pinyin: "xìng", meaning: "họ" },
        { word: "休息", pinyin: "xiūxi", meaning: "nghỉ ngơi" },
        { word: "雪", pinyin: "xuě", meaning: "tuyết" },
        { word: "颜色", pinyin: "yánsè", meaning: "màu sắc" },
        { word: "眼睛", pinyin: "yǎnjing", meaning: "mắt" },
        { word: "羊肉", pinyin: "yángròu", meaning: "thịt cừu, thịt dê" },
        { word: "药", pinyin: "yào", meaning: "thuốc" },
        { word: "要", pinyin: "yào", meaning: "muốn, phải, cần" },
        { word: "也", pinyin: "yě", meaning: "cũng" },
        { word: "一起", pinyin: "yìqǐ", meaning: "cùng nhau" },
        { word: "一下", pinyin: "yíxià", meaning: "một chút, một lát" },
        { word: "意思", pinyin: "yìsi", meaning: "ý nghĩa" },
        { word: "因为", pinyin: "yīnwèi", meaning: "bởi vì" },
        { word: "所以", pinyin: "suǒyǐ", meaning: "cho nên" },
        { word: "阴", pinyin: "yīn", meaning: "âm, nhiều mây, râm" },
        { word: "游泳", pinyin: "yóuyǒng", meaning: "bơi lội" },
        { word: "右边", pinyin: "yòubian", meaning: "bên phải" },
        { word: "鱼", pinyin: "yú", meaning: "cá" },
        { word: "远", pinyin: "yuǎn", meaning: "xa" },
        { word: "运动", pinyin: "yùndòng", meaning: "vận động, thể thao" },
        { word: "再", pinyin: "zài", meaning: "lại, nữa" },
        { word: "早上", pinyin: "zǎoshang", meaning: "buổi sáng sớm" },
        { word: "丈夫", pinyin: "zhàngfu", meaning: "chồng" },
        { word: "找", pinyin: "zhǎo", meaning: "tìm" },
        { word: "着", pinyin: "zhe", meaning: "đang (trợ từ)" },
        { word: "真", pinyin: "zhēn", meaning: "thật, thật là" },
        { word: "正在", pinyin: "zhèngzài", meaning: "đang" },
        { word: "知道", pinyin: "zhīdào", meaning: "biết" },
        { word: "准备", pinyin: "zhǔnbèi", meaning: "chuẩn bị" },
        { word: "自行车", pinyin: "zìxíngchē", meaning: "xe đạp" },
        { word: "走", pinyin: "zǒu", meaning: "đi, đi bộ" },
        { word: "最", pinyin: "zuì", meaning: "nhất" },
        { word: "左边", pinyin: "zuǒbian", meaning: "bên trái" },
        { word: "已经", pinyin: "yǐjīng", meaning: "đã" },
        { word: "但是", pinyin: "dànshì", meaning: "nhưng" }
    ]
    
};
// Dữ liệu Từ vựng HSK 3 (Đầy đủ 300/300 từ)
hskData["3"] = [
    { word: "阿姨", pinyin: "āyí", meaning: "dì, cô, bác gái" },
    { word: "啊", pinyin: "a", meaning: "à, ơ (thán từ)" },
    { word: "矮", pinyin: "ǎi", meaning: "thấp, lùn" },
    { word: "爱好", pinyin: "àihào", meaning: "sở thích" },
    { word: "安静", pinyin: "ānjìng", meaning: "yên tĩnh" },
    { word: "把", pinyin: "bǎ", meaning: "cầm, nắm; trợ từ câu chữ 把" },
    { word: "搬", pinyin: "bān", meaning: "chuyển, dời" },
    { word: "班", pinyin: "bān", meaning: "lớp, ca làm việc" },
    { word: "办法", pinyin: "bànfǎ", meaning: "biện pháp, cách" },
    { word: "办公室", pinyin: "bàngōngshì", meaning: "văn phòng" },
    { word: "半", pinyin: "bàn", meaning: "nửa, rưỡi" },
    { word: "帮忙", pinyin: "bāngmáng", meaning: "giúp đỡ" },
    { word: "包", pinyin: "bāo", meaning: "túi, bao, gói" },
    { word: "饱", pinyin: "bǎo", meaning: "no" },
    { word: "北方", pinyin: "běifāng", meaning: "phương Bắc, miền Bắc" },
    { word: "被", pinyin: "bèi", meaning: "bị, được (câu bị động)" },
    { word: "鼻子", pinyin: "bízi", meaning: "cái mũi" },
    { word: "比较", pinyin: "bǐjiào", meaning: "so sánh, tương đối, khá" },
    { word: "比赛", pinyin: "bǐsài", meaning: "thi đấu, cuộc thi" },
    { word: "笔记本", pinyin: "bǐjìběn", meaning: "sổ tay, máy tính xách tay" },
    { word: "必须", pinyin: "bìxū", meaning: "phải, bắt buộc" },
    { word: "变化", pinyin: "biànhuà", meaning: "thay đổi, biến hóa" },
    { word: "别人", pinyin: "biéren", meaning: "người khác" },
    { word: "冰箱", pinyin: "bīngxiāng", meaning: "tủ lạnh" },
    { word: "不但", pinyin: "búdàn", meaning: "không những" },
    { word: "而且", pinyin: "érqiě", meaning: "mà còn" },
    { word: "菜单", pinyin: "càidān", meaning: "thực đơn" },
    { word: "参加", pinyin: "cānjiā", meaning: "tham gia" },
    { word: "草", pinyin: "cǎo", meaning: "cỏ" },
    { word: "层", pinyin: "céng", meaning: "tầng, lớp" },
    { word: "差", pinyin: "chà", meaning: "kém, thiếu" },
    { word: "超市", pinyin: "chāoshì", meaning: "siêu thị" },
    { word: "衬衫", pinyin: "chènshān", meaning: "áo sơ mi" },
    { word: "成绩", pinyin: "chéngjì", meaning: "thành tích, kết quả" },
    { word: "城市", pinyin: "chéngshì", meaning: "thành phố" },
    { word: "迟到", pinyin: "chídào", meaning: "đến muộn, trễ" },
    { word: "出现", pinyin: "chūxiàn", meaning: "xuất hiện" },
    { word: "厨房", pinyin: "chúfáng", meaning: "nhà bếp" },
    { word: "除了", pinyin: "chúle", meaning: "ngoài ra, trừ ra" },
    { word: "春", pinyin: "chūn", meaning: "mùa xuân" },
    { word: "词典", pinyin: "cídiǎn", meaning: "từ điển" },
    { word: "聪明", pinyin: "cōngming", meaning: "thông minh" },
    { word: "打扫", pinyin: "dǎsǎo", meaning: "quét dọn, vệ sinh" },
    { word: "打算", pinyin: "dǎsuàn", meaning: "dự định, tính toán" },
    { word: "带", pinyin: "dài", meaning: "mang, đem, dẫn" },
    { word: "担心", pinyin: "dānxīn", meaning: "lo lắng" },
    { word: "蛋糕", pinyin: "dàngāo", meaning: "bánh ngọt, bánh kem" },
    { word: "当然", pinyin: "dāngrán", meaning: "đương nhiên, tất nhiên" },
    { word: "地", pinyin: "de", meaning: "trợ từ (đứng trước động từ)" },
    { word: "灯", pinyin: "dēng", meaning: "cái đèn" },
    { word: "地方", pinyin: "dìfang", meaning: "địa phương, nơi, chỗ" },
    { word: "地铁", pinyin: "dìtiě", meaning: "tàu điện ngầm" },
    { word: "地图", pinyin: "dìtú", meaning: "bản đồ" },
    { word: "电梯", pinyin: "diàntī", meaning: "thang máy" },
    { word: "电子邮件", pinyin: "diànzǐ yóujiàn", meaning: "thư điện tử (email)" },
    { word: "东", pinyin: "dōng", meaning: "phía Đông" },
    { word: "冬", pinyin: "dōng", meaning: "mùa đông" },
    { word: "动物", pinyin: "dòngwù", meaning: "động vật" },
    { word: "短", pinyin: "duǎn", meaning: "ngắn" },
    { word: "段", pinyin: "duàn", meaning: "đoạn, khúc" },
    { word: "锻炼", pinyin: "duànliàn", meaning: "rèn luyện, tập thể dục" },
    { word: "多么", pinyin: "duōme", meaning: "bao nhiêu, biết bao" },
    { word: "饿", pinyin: "è", meaning: "đói" },
    { word: "耳朵", pinyin: "ěrduo", meaning: "cái tai" },
    { word: "发烧", pinyin: "fāshāo", meaning: "phát sốt, sốt" },
    { word: "发现", pinyin: "fāxiàn", meaning: "phát hiện" },
    { word: "方便", pinyin: "fāngbiàn", meaning: "thuận tiện, tiện lợi" },
    { word: "放", pinyin: "fàng", meaning: "thả, đặt, để" },
    { word: "放心", pinyin: "fàngxīn", meaning: "yên tâm" },
    { word: "分", pinyin: "fēn", meaning: "phút, điểm, chia" },
    { word: "附近", pinyin: "fùjìn", meaning: "lân cận, gần đây" },
    { word: "复习", pinyin: "fùxí", meaning: "ôn tập" },
    { word: "干净", pinyin: "gānjìng", meaning: "sạch sẽ" },
    { word: "感冒", pinyin: "gǎnmào", meaning: "cảm cúm" },
    { word: "感兴趣", pinyin: "gǎn xīngqù", meaning: "hứng thú, quan tâm" },
    { word: "刚才", pinyin: "gāngcái", meaning: "vừa mới, vừa lúc nãy" },
    { word: "个子", pinyin: "gèzi", meaning: "vóc dáng, chiều cao" },
    { word: "根据", pinyin: "gēnjù", meaning: "căn cứ, dựa vào" },
    { word: "跟", pinyin: "gēn", meaning: "cùng, với, đi theo" },
    { word: "更", pinyin: "gèng", meaning: "càng, hơn nữa" },
    { word: "公园", pinyin: "gōngyuán", meaning: "công viên" },
    { word: "故事", pinyin: "gùshi", meaning: "câu chuyện" },
    { word: "刮风", pinyin: "guāfēng", meaning: "nổi gió, gió thổi" },
    { word: "关", pinyin: "guān", meaning: "đóng, tắt" },
    { word: "关系", pinyin: "guānxi", meaning: "quan hệ" },
    { word: "关心", pinyin: "guānxīn", meaning: "quan tâm" },
    { word: "关于", pinyin: "guānyú", meaning: "về, liên quan đến" },
    { word: "国家", pinyin: "guójiā", meaning: "quốc gia, đất nước" },
    { word: "果汁", pinyin: "guǒzhī", meaning: "nước trái cây" },
    { word: "过去", pinyin: "guòqù", meaning: "quá khứ, trước đây" },
    { word: "还是", pinyin: "háishi", meaning: "hay là, vẫn" },
    { word: "害怕", pinyin: "hàipà", meaning: "sợ hãi" },
    { word: "黑板", pinyin: "hēibǎn", meaning: "bảng đen" },
    { word: "护照", pinyin: "hùzhào", meaning: "hộ chiếu" },
    { word: "花", pinyin: "huā", meaning: "hoa; tiêu (tiền/thời gian)" },
    { word: "花园", pinyin: "huāyuán", meaning: "vườn hoa" },
    { word: "画", pinyin: "huà", meaning: "vẽ, bức tranh" },
    { word: "坏", pinyin: "huài", meaning: "hỏng, xấu, tồi" },
    { word: "环境", pinyin: "huánjìng", meaning: "môi trường, hoàn cảnh" },
    { word: "换", pinyin: "huàn", meaning: "đổi, thay" },
    { word: "黄", pinyin: "huáng", meaning: "màu vàng" },
    { word: "会议", pinyin: "huìyì", meaning: "cuộc họp, hội nghị" },
    { word: "回忆", pinyin: "huíyì", meaning: "hồi ức, nhớ lại" },
    { word: "活动", pinyin: "huódòng", meaning: "hoạt động" },
    { word: "火车站", pinyin: "huǒchēzhàn", meaning: "ga tàu hỏa" },
    { word: "几乎", pinyin: "jīhū", meaning: "hầu như, gần như" },
    { word: "机会", pinyin: "jīhuì", meaning: "cơ hội" },
    { word: "极", pinyin: "jí", meaning: "cực kỳ, vô cùng" },
    { word: "季节", pinyin: "jìjié", meaning: "mùa (trong năm)" },
    { word: "检查", pinyin: "jiǎnchá", meaning: "kiểm tra" },
    { word: "简单", pinyin: "jiǎndān", meaning: "đơn giản" },
    { word: "健康", pinyin: "jiànkāng", meaning: "khỏe mạnh, sức khỏe" },
    { word: "见面", pinyin: "jiànmiàn", meaning: "gặp mặt" },
    { word: "讲", pinyin: "jiǎng", meaning: "nói, giảng giải" },
    { word: "教", pinyin: "jiāo", meaning: "dạy học" },
    { word: "脚", pinyin: "jiǎo", meaning: "bàn chân" },
    { word: "角", pinyin: "jiǎo", meaning: "hào (1/10 tệ), góc" },
    { word: "接", pinyin: "jiē", meaning: "đón, nhận (điện thoại)" },
    { word: "街道", pinyin: "jiēdào", meaning: "đường phố" },
    { word: "结婚", pinyin: "jiéhūn", meaning: "kết hôn" },
    { word: "结束", pinyin: "jiéshù", meaning: "kết thúc" },
    { word: "节目", pinyin: "jiémù", meaning: "chương trình" },
    { word: "节日", pinyin: "jiérì", meaning: "ngày lễ, ngày tết" },
    { word: "解决", pinyin: "jiějué", meaning: "giải quyết" },
    { word: "借", pinyin: "jiè", meaning: "mượn, vay" },
    { word: "经常", pinyin: "jīngcháng", meaning: "thường xuyên" },
    { word: "经过", pinyin: "jīngguò", meaning: "trải qua, đi qua" },
    { word: "经理", pinyin: "jīnglǐ", meaning: "giám đốc, quản lý" },
    { word: "久", pinyin: "jiǔ", meaning: "lâu" },
    { word: "旧", pinyin: "jiù", meaning: "cũ" },
    { word: "句子", pinyin: "jùzi", meaning: "câu (văn)" },
    { word: "决定", pinyin: "juédìng", meaning: "quyết định" },
    { word: "可爱", pinyin: "kě'ài", meaning: "đáng yêu" },
    { word: "渴", pinyin: "kě", meaning: "khát" },
    { word: "刻", pinyin: "kè", meaning: "khắc (15 phút)" },
    { word: "客人", pinyin: "kèrén", meaning: "khách, khách hàng" },
    { word: "空调", pinyin: "kōngtiáo", meaning: "điều hòa" },
    { word: "口", pinyin: "kǒu", meaning: "miệng; lượng từ (người)" },
    { word: "哭", pinyin: "kū", meaning: "khóc" },
    { word: "裤子", pinyin: "kùzi", meaning: "chiếc quần" },
    { word: "筷子", pinyin: "kuàizi", meaning: "đôi đũa" },
    { word: "蓝", pinyin: "lán", meaning: "màu xanh lam" },
    { word: "老", pinyin: "lǎo", meaning: "già, cũ" },
    { word: "离开", pinyin: "líkāi", meaning: "rời khỏi, chia tay" },
    { word: "礼物", pinyin: "lǐwù", meaning: "quà tặng" },
    { word: "历史", pinyin: "lìshǐ", meaning: "lịch sử" },
    { word: "脸", pinyin: "liǎn", meaning: "khuôn mặt" },
    { word: "练习", pinyin: "liànxí", meaning: "luyện tập, bài tập" },
    { word: "辆", pinyin: "liàng", meaning: "chiếc (xe)" },
    { word: "了解", pinyin: "liǎojiě", meaning: "hiểu rõ, tìm hiểu" },
    { word: "邻居", pinyin: "línjū", meaning: "hàng xóm" },
    { word: "留学", pinyin: "liúxué", meaning: "du học" },
    { word: "楼", pinyin: "lóu", meaning: "tòa nhà, tầng" },
    { word: "绿", pinyin: "lǜ", meaning: "màu xanh lá" },
    { word: "马", pinyin: "mǎ", meaning: "con ngựa" },
    { word: "马上", pinyin: "mǎshàng", meaning: "ngay lập tức" },
    { word: "满意", pinyin: "mǎnyì", meaning: "hài lòng" },
    { word: "帽子", pinyin: "màozi", meaning: "cái mũ, nón" },
    { word: "米", pinyin: "mǐ", meaning: "mét; gạo" },
    { word: "面包", pinyin: "miànbāo", meaning: "bánh mì" },
    { word: "面条", pinyin: "miàntiáo", meaning: "mì sợi" },
    { word: "明白", pinyin: "míngbai", meaning: "hiểu, rõ ràng" },
    { word: "拿", pinyin: "ná", meaning: "cầm, nắm, lấy" },
    { word: "奶奶", pinyin: "nǎinai", meaning: "bà nội" },
    { word: "南", pinyin: "nán", meaning: "phía Nam" },
    { word: "难", pinyin: "nán", meaning: "khó" },
    { word: "难过", pinyin: "nánguò", meaning: "buồn bã, khó chịu" },
    { word: "年级", pinyin: "niánjí", meaning: "khối, lớp" },
    { word: "年轻", pinyin: "niánqīng", meaning: "trẻ tuổi" },
    { word: "鸟", pinyin: "niǎo", meaning: "con chim" },
    { word: "努力", pinyin: "nǔlì", meaning: "nỗ lực, cố gắng" },
    { word: "爬山", pinyin: "páshān", meaning: "leo núi" },
    { word: "盘子", pinyin: "pánzi", meaning: "cái đĩa" },
    { word: "胖", pinyin: "pàng", meaning: "béo, mập" },
    { word: "皮鞋", pinyin: "píxié", meaning: "giày da" },
    { word: "啤酒", pinyin: "píjiǔ", meaning: "bia" },
    { word: "普通话", pinyin: "pǔtōnghuà", meaning: "tiếng phổ thông" },
    { word: "其实", pinyin: "qíshí", meaning: "thực ra, thực chất" },
    { word: "其他", pinyin: "qítā", meaning: "cái khác, người khác" },
    { word: "骑", pinyin: "qí", meaning: "cưỡi, đi (xe đạp/máy)" },
    { word: "起飞", pinyin: "qǐfēi", meaning: "cất cánh" },
    { word: "起来", pinyin: "qǐlái", meaning: "đứng dậy, nhô lên" },
    { word: "清楚", pinyin: "qīngchu", meaning: "rõ ràng" },
    { word: "请假", pinyin: "qǐngjià", meaning: "xin nghỉ phép" },
    { word: "秋", pinyin: "qiū", meaning: "mùa thu" },
    { word: "裙子", pinyin: "qúnzi", meaning: "cái váy" },
    { word: "然后", pinyin: "ránhòu", meaning: "sau đó" },
    { word: "热情", pinyin: "rèqíng", meaning: "nhiệt tình" },
    { word: "认为", pinyin: "rènwéi", meaning: "cho rằng, nghĩ rằng" },
    { word: "认真", pinyin: "rènzhēn", meaning: "nghiêm túc, chăm chỉ" },
    { word: "容易", pinyin: "róngyì", meaning: "dễ dàng" },
    { word: "如果", pinyin: "rúguǒ", meaning: "nếu, nếu như" },
    { word: "伞", pinyin: "sǎn", meaning: "cái ô, cái dù" },
    { word: "上网", pinyin: "shàngwǎng", meaning: "lên mạng, truy cập internet" },
    { word: "生气", pinyin: "shēngqì", meaning: "tức giận" },
    { word: "声音", pinyin: "shēngyīn", meaning: "âm thanh, tiếng" },
    { word: "使", pinyin: "shǐ", meaning: "khiến cho, làm cho" },
    { word: "世界", pinyin: "shìjiè", meaning: "thế giới" },
    { word: "瘦", pinyin: "shòu", meaning: "gầy, ốm" },
    { word: "叔叔", pinyin: "shūshu", meaning: "chú, bác" },
    { word: "舒服", pinyin: "shūfu", meaning: "thoải mái, dễ chịu" },
    { word: "树", pinyin: "shù", meaning: "cái cây" },
    { word: "数学", pinyin: "shùxué", meaning: "môn toán" },
    { word: "刷牙", pinyin: "shuāyá", meaning: "đánh răng" },
    { word: "双", pinyin: "shuāng", meaning: "đôi, cặp" },
    { word: "水平", pinyin: "shuǐpíng", meaning: "trình độ" },
    { word: "司机", pinyin: "sījī", meaning: "tài xế" },
    { word: "太阳", pinyin: "tàiyáng", meaning: "mặt trời" },
    { word: "特别", pinyin: "tèbié", meaning: "đặc biệt" },
    { word: "疼", pinyin: "téng", meaning: "đau" },
    { word: "提高", pinyin: "tígāo", meaning: "nâng cao" },
    { word: "体育", pinyin: "tǐyù", meaning: "thể dục, thể thao" },
    { word: "甜", pinyin: "tián", meaning: "ngọt" },
    { word: "条", pinyin: "tiáo", meaning: "con, chiếc (lượng từ vật dài)" },
    { word: "同意", pinyin: "tóngyì", meaning: "đồng ý" },
    { word: "头发", pinyin: "tóufa", meaning: "tóc" },
    { word: "突然", pinyin: "tūrán", meaning: "đột nhiên, bất ngờ" },
    { word: "图书馆", pinyin: "túshūguǎn", meaning: "thư viện" },
    { word: "腿", pinyin: "tuǐ", meaning: "cái chân" },
    { word: "完成", pinyin: "wánchéng", meaning: "hoàn thành" },
    { word: "碗", pinyin: "wǎn", meaning: "cái bát, chén" },
    { word: "万", pinyin: "wàn", meaning: "vạn, mười nghìn" },
    { word: "忘记", pinyin: "wàngjì", meaning: "quên" },
    { word: "为", pinyin: "wèi", meaning: "vì, để" },
    { word: "为了", pinyin: "wèile", meaning: "để, vì" },
    { word: "位", pinyin: "wèi", meaning: "vị (kính ngữ cho người)" },
    { word: "文化", pinyin: "wénhuà", meaning: "văn hóa" },
    { word: "西", pinyin: "xī", meaning: "phía Tây" },
    { word: "习惯", pinyin: "xíguàn", meaning: "thói quen, quen" },
    { word: "洗手间", pinyin: "xǐshǒujiān", meaning: "nhà vệ sinh" },
    { word: "洗澡", pinyin: "xǐzǎo", meaning: "tắm" },
    { word: "夏", pinyin: "xià", meaning: "mùa hè" },
    { word: "先", pinyin: "xiān", meaning: "trước, trước tiên" },
    { word: "相信", pinyin: "xiāngxìn", meaning: "tin tưởng" },
    { word: "香蕉", pinyin: "xiāngjiāo", meaning: "quả chuối" },
    { word: "向", pinyin: "xiàng", meaning: "hướng về, về phía" },
    { word: "像", pinyin: "xiàng", meaning: "giống như" },
    { word: "小心", pinyin: "xiǎoxīn", meaning: "cẩn thận" },
    { word: "校长", pinyin: "xiàozhǎng", meaning: "hiệu trưởng" },
    { word: "新闻", pinyin: "xīnwén", meaning: "tin tức" },
    { word: "新鲜", pinyin: "xīnxiān", meaning: "tươi mới, tươi ngon" },
    { word: "信用卡", pinyin: "xìnyòngkǎ", meaning: "thẻ tín dụng" },
    { word: "行李箱", pinyin: "xínglixiāng", meaning: "va li" },
    { word: "熊猫", pinyin: "xióngmāo", meaning: "gấu trúc" },
    { word: "需要", pinyin: "xūyào", meaning: "cần, nhu cầu" },
    { word: "选择", pinyin: "xuǎnzé", meaning: "lựa chọn" },
    { word: "眼镜", pinyin: "yǎnjìng", meaning: "kính mắt" },
    { word: "要求", pinyin: "yāoqiú", meaning: "yêu cầu" },
    { word: "爷爷", pinyin: "yéye", meaning: "ông nội" },
    { word: "一定", pinyin: "yídìng", meaning: "nhất định" },
    { word: "一共", pinyin: "yígòng", meaning: "tổng cộng" },
    { word: "一会儿", pinyin: "yíhuìr", meaning: "một lúc, một lát" },
    { word: "一样", pinyin: "yíyàng", meaning: "giống nhau" },
    { word: "一直", pinyin: "yìzhí", meaning: "luôn luôn, thẳng" },
    { word: "以前", pinyin: "yǐqián", meaning: "trước đây" },
    { word: "一般", pinyin: "yìbān", meaning: "bình thường, phổ biến" },
    { word: "音乐", pinyin: "yīnyuè", meaning: "âm nhạc" },
    { word: "银行", pinyin: "yínháng", meaning: "ngân hàng" },
    { word: "饮料", pinyin: "yǐnliào", meaning: "đồ uống, nước giải khát" },
    { word: "影响", pinyin: "yǐngxiǎng", meaning: "ảnh hưởng" },
    { word: "用", pinyin: "yòng", meaning: "dùng, sử dụng" },
    { word: "游戏", pinyin: "yóuxì", meaning: "trò chơi, game" },
    { word: "有名", pinyin: "yǒumíng", meaning: "nổi tiếng" },
    { word: "又", pinyin: "yòu", meaning: "lại (đã xảy ra)" },
    { word: "遇到", pinyin: "yùdào", meaning: "gặp phải, bắt gặp" },
    { word: "元", pinyin: "yuán", meaning: "đồng (đơn vị tiền)" },
    { word: "愿意", pinyin: "yuànyì", meaning: "tự nguyện, bằng lòng" },
    { word: "月亮", pinyin: "yuèliang", meaning: "mặt trăng" },
    { word: "越", pinyin: "yuè", meaning: "càng" },
    { word: "云", pinyin: "yún", meaning: "mây" },
    { word: "站", pinyin: "zhàn", meaning: "trạm, bến, đứng" },
    { word: "张", pinyin: "zhāng", meaning: "tờ, tấm (lượng từ)" },
    { word: "照顾", pinyin: "zhàogù", meaning: "chăm sóc, chiếu cố" },
    { word: "照片", pinyin: "zhàopiàn", meaning: "bức ảnh" },
    { word: "相机", pinyin: "xiàngjī", meaning: "máy ảnh" },
    { word: "只", pinyin: "zhǐ", meaning: "chỉ (chỉ có)" },
    { word: "只", pinyin: "zhī", meaning: "con (lượng từ động vật)" },
    { word: "中间", pinyin: "zhōngjiān", meaning: "ở giữa" },
    { word: "中文", pinyin: "zhōngwén", meaning: "tiếng Trung" },
    { word: "终于", pinyin: "zhōngyú", meaning: "cuối cùng thì" },
    { word: "种", pinyin: "zhǒng", meaning: "loại, loại hình" },
    { word: "重要", pinyin: "zhòngyào", meaning: "quan trọng" },
    { word: "周末", pinyin: "zhōumò", meaning: "cuối tuần" },
    { word: "主要", pinyin: "zhǔyào", meaning: "chủ yếu, chính" },
    { word: "注意", pinyin: "zhùyì", meaning: "chú ý" },
    { word: "着急", pinyin: "zháojí", meaning: "sốt ruột, lo lắng" },
    { word: "自己", pinyin: "zìjǐ", meaning: "tự mình, bản thân" },
    { word: "总是", pinyin: "zǒngshì", meaning: "luôn luôn" },
    { word: "嘴", pinyin: "zuǐ", meaning: "miệng, môi" },
    { word: "作业", pinyin: "zuòyè", meaning: "bài tập về nhà" },
    { word: "作用", pinyin: "zuòyòng", meaning: "tác dụng, ảnh hưởng" }
];

// Dữ liệu Từ vựng HSK 4 (Đầy đủ 600/600 từ)
hskData["4"] = [
    { word: "爱情", pinyin: "àiqíng", meaning: "tình yêu" },
    { word: "安排", pinyin: "ānpái", meaning: "an bài, sắp xếp" },
    { word: "安全", pinyin: "ānquán", meaning: "an toàn" },
    { word: "暗", pinyin: "àn", meaning: "tối, u ám" },
    { word: "按时", pinyin: "ànshí", meaning: "đúng giờ" },
    { word: "按照", pinyin: "ànzhào", meaning: "dựa theo, chiếu theo" },
    { word: "抱", pinyin: "bào", meaning: "ôm, bế" },
    { word: "抱歉", pinyin: "bàoqiàn", meaning: "xin lỗi, lấy làm tiếc" },
    { word: "保护", pinyin: "bǎohù", meaning: "bảo vệ" },
    { word: "报名", pinyin: "bàomíng", meaning: "đăng ký" },
    { word: "包子", pinyin: "bāozi", meaning: "bánh bao" },
    { word: "保证", pinyin: "bǎozhèng", meaning: "bảo đảm, cam đoan" },
    { word: "本来", pinyin: "běnlái", meaning: "vốn dĩ, ban đầu" },
    { word: "笨", pinyin: "bèn", meaning: "ngốc nghếch, ngớ ngẩn" },
    { word: "比如", pinyin: "bǐrú", meaning: "ví dụ như" },
    { word: "毕业", pinyin: "bìyè", meaning: "tốt nghiệp" },
    { word: "遍", pinyin: "biàn", meaning: "lần, lượt (từ đầu đến cuối)" },
    { word: "标准", pinyin: "biāozhǔn", meaning: "tiêu chuẩn" },
    { word: "表格", pinyin: "biǎogé", meaning: "bảng biểu, biểu mẫu" },
    { word: "表示", pinyin: "biǎoshì", meaning: "biểu thị, bày tỏ" },
    { word: "表演", pinyin: "biǎoyǎn", meaning: "biểu diễn" },
    { word: "表扬", pinyin: "biǎoyáng", meaning: "khen ngợi, biểu dương" },
    { word: "饼干", pinyin: "bǐnggān", meaning: "bánh quy" },
    { word: "并且", pinyin: "bìngqiě", meaning: "đồng thời, hơn nữa" },
    { word: "博士", pinyin: "bóshì", meaning: "tiến sĩ" },
    { word: "不过", pinyin: "búguò", meaning: "nhưng, có điều" },
    { word: "不得不", pinyin: "bùdébù", meaning: "không thể không, đành phải" },
    { word: "不管", pinyin: "bùguǎn", meaning: "cho dù, bất luận" },
    { word: "不好意思", pinyin: "bù hǎoyìsi", meaning: "ngại ngùng, xin lỗi" },
    { word: "不仅", pinyin: "bùjǐn", meaning: "không chỉ" },
    { word: "部分", pinyin: "bùfen", meaning: "bộ phận, phần" },
    { word: "擦", pinyin: "cā", meaning: "lau, chùi, xát" },
    { word: "猜", pinyin: "cāi", meaning: "đoán" },
    { word: "材料", pinyin: "cáiliào", meaning: "tài liệu, vật liệu" },
    { word: "参观", pinyin: "cānguān", meaning: "tham quan" },
    { word: "餐厅", pinyin: "cāntīng", meaning: "nhà hàng, phòng ăn" },
    { word: "厕所", pinyin: "cèsuǒ", meaning: "nhà vệ sinh" },
    { word: "差不多", pinyin: "chàbuduō", meaning: "xấp xỉ, gần như" },
    { word: "长城", pinyin: "Chángchéng", meaning: "Vạn Lý Trường Thành" },
    { word: "长江", pinyin: "Chángjiāng", meaning: "sông Trường Giang" },
    { word: "尝", pinyin: "cháng", meaning: "nếm, thử" },
    { word: "场", pinyin: "chǎng", meaning: "trận, hiệp, sân" },
    { word: "超过", pinyin: "chāoguò", meaning: "vượt quá" },
    { word: "成功", pinyin: "chénggōng", meaning: "thành công" },
    { word: "成熟", pinyin: "chéngshú", meaning: "trưởng thành, chín" },
    { word: "成为", pinyin: "chéngwéi", meaning: "trở thành" },
    { word: "诚实", pinyin: "chéngshí", meaning: "thành thật, trung thực" },
    { word: "乘坐", pinyin: "chéngzuò", meaning: "ngồi, đi (tàu, xe, máy bay)" },
    { word: "吃惊", pinyin: "chījīng", meaning: "giật mình, kinh ngạc" },
    { word: "重新", pinyin: "chóngxīn", meaning: "làm lại từ đầu" },
    { word: "抽烟", pinyin: "chōuyān", meaning: "hút thuốc" },
    { word: "出差", pinyin: "chūchāi", meaning: "đi công tác" },
    { word: "出发", pinyin: "chūfā", meaning: "xuất phát" },
    { word: "出生", pinyin: "chūshēng", meaning: "sinh ra" },
    { word: "厨房", pinyin: "chúfáng", meaning: "bếp" },
    { word: "传真", pinyin: "chuánzhēn", meaning: "fax, gửi bản sao" },
    { word: "词语", pinyin: "cíyǔ", meaning: "từ ngữ" },
    { word: "粗心", pinyin: "cūxīn", meaning: "cẩu thả, bất cẩn" },
    { word: "存", pinyin: "cún", meaning: "gửi, tồn, lưu trữ" },
    { word: "错误", pinyin: "cuòwù", meaning: "sai lầm, lỗi sai" },
    { word: "答案", pinyin: "dá'àn", meaning: "đáp án" },
    { word: "打扮", pinyin: "dǎban", meaning: "trang điểm, ăn diện" },
    { word: "打扰", pinyin: "dǎrǎo", meaning: "làm phiền" },
    { word: "打折", pinyin: "dǎzhé", meaning: "giảm giá" },
    { word: "打针", pinyin: "dǎzhēn", meaning: "tiêm, chích thuốc" },
    { word: "大概", pinyin: "dàgài", meaning: "đại khái, khoảng" },
    { word: "大使馆", pinyin: "dàshǐguǎn", meaning: "đại sứ quán" },
    { word: "大约", pinyin: "dàyuē", meaning: "khoảng chừng" },
    { word: "戴", pinyin: "dài", meaning: "đeo, đội (kính, mũ, đồng hồ)" },
    { word: "当", pinyin: "dāng", meaning: "làm (nghề); khi" },
    { word: "当时", pinyin: "dāngshí", meaning: "lúc đó, khi đó" },
    { word: "刀", pinyin: "dāo", meaning: "con dao" },
    { word: "导游", pinyin: "dǎoyóu", meaning: "hướng dẫn viên du lịch" },
    { word: "到处", pinyin: "dàochù", meaning: "khắp nơi, mọi nơi" },
    { word: "到底", pinyin: "dàodǐ", meaning: "rốt cuộc, đến cùng" },
    { word: "道歉", pinyin: "dàoqiàn", meaning: "xin lỗi" },
    { word: "得意", pinyin: "déyì", meaning: "đắc ý, đắc thắng" },
    { word: "得", pinyin: "děi", meaning: "phải, cần phải" },
    { word: "登机牌", pinyin: "dēngjīpái", meaning: "thẻ lên máy bay" },
    { word: "等", pinyin: "děng", meaning: "vân vân, bằng nhau" },
    { word: "低", pinyin: "dī", meaning: "thấp, cúi" },
    { word: "底", pinyin: "dǐ", meaning: "đáy, cuối (tháng/năm)" },
    { word: "地点", pinyin: "dìdiǎn", meaning: "địa điểm" },
    { word: "地球", pinyin: "dìqiú", meaning: "trái đất" },
    { word: "地址", pinyin: "dìzhǐ", meaning: "địa chỉ" },
    { word: "调查", pinyin: "diàochá", meaning: "điều tra, khảo sát" },
    { word: "掉", pinyin: "diào", meaning: "rơi, rụng, mất" },
    { word: "丢", pinyin: "diū", meaning: "mất, ném, vứt" },
    { word: "动作", pinyin: "dòngzuò", meaning: "động tác" },
    { word: "堵车", pinyin: "dǔchē", meaning: "tắc đường, kẹt xe" },
    { word: "肚子", pinyin: "dùzi", meaning: "bụng" },
    { word: "断", pinyin: "duàn", meaning: "gãy, đứt, cắt" },
    { word: "对话", pinyin: "duìhuà", meaning: "đối thoại, hội thoại" },
    { word: "对面", pinyin: "duìmiàn", meaning: "đối diện" },
    { word: "顿", pinyin: "dùn", meaning: "bữa, trận (lượng từ ăn/mắng)" },
    { word: "朵", pinyin: "duǒ", meaning: "bông, đóa (lượng từ hoa, mây)" },
    { word: "儿童", pinyin: "értóng", meaning: "nhi đồng, trẻ em" },
    { word: "而", pinyin: "ér", meaning: "và, mà, nhưng" },
    { word: "发", pinyin: "fā", meaning: "gửi, phát" },
    { word: "发生", pinyin: "fāshēng", meaning: "phát sinh, xảy ra" },
    { word: "发展", pinyin: "fāzhǎn", meaning: "phát triển" },
    { word: "法律", pinyin: "fǎlǜ", meaning: "pháp luật" },
    { word: "翻译", pinyin: "fānyì", meaning: "phiên dịch, dịch" },
    { word: "烦恼", pinyin: "fánnǎo", meaning: "phiền não, phiền muộn" },
    { word: "反对", pinyin: "fǎnduì", meaning: "phản đối" },
    { word: "方法", pinyin: "fāngfǎ", meaning: "phương pháp" },
    { word: "方面", pinyin: "fāngmiàn", meaning: "phương diện, khía cạnh" },
    { word: "方向", pinyin: "fāngxiàng", meaning: "phương hướng" },
    { word: "房东", pinyin: "fángdōng", meaning: "chủ nhà" },
    { word: "放弃", pinyin: "fàngqì", meaning: "từ bỏ, bỏ cuộc" },
    { word: "放暑假", pinyin: "fàng shǔjià", meaning: "nghỉ hè" },
    { word: "份", pinyin: "fèn", meaning: "phần, bản (lượng từ tài liệu/báo)" },
    { word: "丰富", pinyin: "fēngfù", meaning: "phong phú" },
    { word: "否则", pinyin: "fǒuzé", meaning: "nếu không thì" },
    { word: "符合", pinyin: "fúhé", meaning: "phù hợp" },
    { word: "父亲", pinyin: "fùqīn", meaning: "người bố, cha" },
    { word: "付款", pinyin: "fùkuǎn", meaning: "thanh toán tiền" },
    { word: "负责", pinyin: "fùzé", meaning: "phụ trách, chịu trách nhiệm" },
    { word: "复印", pinyin: "fùyìn", meaning: "photocopy, in sao" },
    { word: "改变", pinyin: "gǎibiàn", meaning: "cải biến, thay đổi" },
    { word: "干杯", pinyin: "gānbēi", meaning: "cạn ly, cụng ly" },
    { word: "干燥", pinyin: "gānzào", meaning: "hanh khô, khô ráo" },
    { word: "感动", pinyin: "gǎndòng", meaning: "cảm động" },
    { word: "感觉", pinyin: "gǎnjué", meaning: "cảm giác, cảm thấy" },
    { word: "感情", pinyin: "gǎnqíng", meaning: "tình cảm" },
    { word: "感谢", pinyin: "gǎnxiè", meaning: "cảm ơn, tạ ơn" },
    { word: "干", pinyin: "gàn", meaning: "làm (công việc)" },
    { word: "高级", pinyin: "gāojí", meaning: "cao cấp" },
    { word: "高速公路", pinyin: "gāosù gōnglù", meaning: "đường cao tốc" },
    { word: "各", pinyin: "gè", meaning: "các, mỗi" },
    { word: "工资", pinyin: "gōngzī", meaning: "tiền lương" },
    { word: "公里", pinyin: "gōnglǐ", meaning: "km, ki-lô-mét" },
    { word: "功夫", pinyin: "gōngfu", meaning: "công phu, võ thuật" },
    { word: "共同", pinyin: "gòngtóng", meaning: "chung, cùng nhau" },
    { word: "购物", pinyin: "gòuwù", meaning: "mua sắm" },
    { word: "够", pinyin: "gòu", meaning: "đủ" },
    { word: "估计", pinyin: "gūjì", meaning: "ước tính, đánh giá" },
    { word: "鼓励", pinyin: "gǔlì", meaning: "khuyến khích, động viên" },
    { word: "故意", pinyin: "gùyì", meaning: "cố ý, cố tình" },
    { word: "顾客", pinyin: "gùkè", meaning: "khách hàng" },
    { word: "挂", pinyin: "guà", meaning: "treo, mắc" },
    { word: "关键", pinyin: "guānjiàn", meaning: "mấu chốt, then chốt" },
    { word: "观众", pinyin: "guānzhòng", meaning: "khán giả" },
    { word: "管理", pinyin: "guǎnlǐ", meaning: "quản lý" },
    { word: "光", pinyin: "guāng", meaning: "ánh sáng, chỉ, hết sạch" },
    { word: "广播", pinyin: "guǎngbō", meaning: "phát thanh, loa" },
    { word: "广告", pinyin: "guǎnggào", meaning: "quảng cáo" },
    { word: "逛", pinyin: "guàng", meaning: "dạo chơi, đi dạo" },
    { word: "规定", pinyin: "guīdìng", meaning: "quy định" },
    { word: "国籍", pinyin: "guójí", meaning: "quốc tịch" },
    { word: "国际", pinyin: "guójì", meaning: "quốc tế" },
    { word: "果汁", pinyin: "guǒzhī", meaning: "nước ép hoa quả" },
    { word: "果然", pinyin: "guǒrán", meaning: "quả nhiên" },
    { word: "过程", pinyin: "guòchéng", meaning: "quá trình" },
    { word: "海洋", pinyin: "hǎiyáng", meaning: "biển cả, đại dương" },
    { word: "害羞", pinyin: "hàixiū", meaning: "xấu hổ, e ngại" },
    { word: "寒假", pinyin: "hánjià", meaning: "nghỉ đông" },
    { word: "汗", pinyin: "hàn", meaning: "mồ hôi" },
    { word: "航班", pinyin: "hángbān", meaning: "chuyến bay" },
    { word: "好处", pinyin: "hǎochu", meaning: "điểm tốt, lợi ích" },
    { word: "好像", pinyin: "hǎoxiàng", meaning: "hình như, dường như" },
    { word: "合格", pinyin: "hégé", meaning: "hợp lệ, đạt tiêu chuẩn" },
    { word: "合适", pinyin: "héshì", meaning: "thích hợp, vừa vặn" },
    { word: "盒子", pinyin: "hézi", meaning: "cái hộp" },
    { word: "猴子", pinyin: "hóuzi", meaning: "con khỉ" },
    { word: "厚", pinyin: "hòu", meaning: "dày" },
    { word: "后悔", pinyin: "hòuhuǐ", meaning: "hối hận" },
    { word: "互联网", pinyin: "hùliánwǎng", meaning: "mạng Internet" },
    { word: "互相", pinyin: "hùxiāng", meaning: "lẫn nhau, qua lại" },
    { word: "护士", pinyin: "hùshi", meaning: "y tá" },
    { word: "怀疑", pinyin: "huáiyí", meaning: "hoài nghi, nghi ngờ" },
    { word: "回忆", pinyin: "huíyì", meaning: "ký ức, nhớ lại" },
    { word: "活动", pinyin: "huódòng", meaning: "hoạt động" },
    { word: "活泼", pinyin: "huópo", meaning: "hoạt bát, năng động" },
    { word: "火", pinyin: "huǒ", meaning: "lửa, hot, nổi tiếng" },
    { word: "获得", pinyin: "huòdé", meaning: "giành được, thu được" },
    { word: "积极", pinyin: "jījí", meaning: "tích cực" },
    { word: "积累", pinyin: "jīlěi", meaning: "tích lũy" },
    { word: "基础", pinyin: "jīchǔ", meaning: "nền tảng, cơ sở" },
    { word: "激动", pinyin: "jīdòng", meaning: "kích động, xúc động" },
    { word: "及时", pinyin: "jíshí", meaning: "kịp thời" },
    { word: "极其", pinyin: "jíqí", meaning: "cực kỳ, rất" },
    { word: "集合", pinyin: "jíhé", meaning: "tập hợp" },
    { word: "计划", pinyin: "jìhuà", meaning: "kế hoạch" },
    { word: "记者", pinyin: "jìzhě", meaning: "phóng viên, nhà báo" },
    { word: "技术", pinyin: "jìshù", meaning: "kỹ thuật, tay nghề" },
    { word: "既然", pinyin: "jìrán", meaning: "đã... thì" },
    { word: "继续", pinyin: "jìxù", meaning: "tiếp tục" },
    { word: "寄", pinyin: "jì", meaning: "gửi (thư, hàng)" },
    { word: "加班", pinyin: "jiābān", meaning: "tăng ca, làm thêm" },
    { word: "加油站", pinyin: "jiāyóuzhàn", meaning: "trạm xăng" },
    { word: "价格", pinyin: "jiàgé", meaning: "giá cả" },
    { word: "假", pinyin: "jiǎ", meaning: "giả, xạo" },
    { word: "坚持", pinyin: "jiānchí", meaning: "kiên trì" },
    { word: "减肥", pinyin: "jiǎnféi", meaning: "giảm cân" },
    { word: "减少", pinyin: "jiǎnshǎo", meaning: "cắt giảm, giảm bớt" },
    { word: "建议", pinyin: "jiànyì", meaning: "kiến nghị, đề xuất" },
    { word: "将来", pinyin: "jiānglái", meaning: "tương lai" },
    { word: "奖金", pinyin: "jiǎngjīn", meaning: "tiền thưởng" },
    { word: "降低", pinyin: "jiàngdī", meaning: "giảm thấp, hạ xuống" },
    { word: "降落", pinyin: "jiàngluò", meaning: "hạ cánh" },
    { word: "交", pinyin: "jiāo", meaning: "giao, nộp, kết bạn" },
    { word: "交流", pinyin: "jiāoliú", meaning: "giao lưu, trao đổi" },
    { word: "交通", pinyin: "jiāotōng", meaning: "giao thông" },
    { word: "郊区", pinyin: "jiāoqū", meaning: "ngoại thành, ngoại ô" },
    { word: "骄傲", pinyin: "jiāo'ào", meaning: "kiêu ngạo, tự hào" },
    { word: "饺子", pinyin: "jiǎozi", meaning: "bánh há cảo, sủi cảo" },
    { word: "教授", pinyin: "jiàoshòu", meaning: "giáo sư" },
    { word: "教育", pinyin: "jiàoyù", meaning: "giáo dục" },
    { word: "接受", pinyin: "jiēshòu", meaning: "tiếp nhận, chấp nhận" },
    { word: "接着", pinyin: "jiēzhe", meaning: "tiếp theo, sau đó" },
    { word: "节", pinyin: "jié", meaning: "tiết (lượng từ tiết học)" },
    { word: "节约", pinyin: "jiéyuē", meaning: "tiết kiệm" },
    { word: "结果", pinyin: "jiéguǒ", meaning: "kết quả" },
    { word: "解释", pinyin: "jiěshì", meaning: "giải thích" },
    { word: "尽管", pinyin: "jǐnguǎn", meaning: "cho dù, mặc dù" },
    { word: "紧张", pinyin: "jǐnzhāng", meaning: "hồi hộp, căng thẳng" },
    { word: "进行", pinyin: "jìnxíng", meaning: "tiến hành" },
    { word: "禁止", pinyin: "jìnzhǐ", meaning: "cấm, cấm đoán" },
    { word: "京剧", pinyin: "jīngjù", meaning: "Kinh kịch Trung Quốc" },
    { word: "精彩", pinyin: "jīngcǎi", meaning: "đặc sắc, tuyệt vời" },
    { word: "经济", pinyin: "jīngjì", meaning: "kinh tế" },
    { word: "经验", pinyin: "jīngyàn", meaning: "kinh nghiệm" },
    { word: "京剧", pinyin: "jīngjù", meaning: "Kinh kịch" },
    { word: "警察", pinyin: "jǐngchá", meaning: "cảnh sát" },
    { word: "竟然", pinyin: "jìngrán", meaning: "mà lại, không ngờ" },
    { word: "竞争", pinyin: "jìngzhēng", meaning: "cạnh tranh" },
    { word: "究竟", pinyin: "jiūjìng", meaning: "rốt cuộc, kết quả" },
    { word: "举办", pinyin: "jǔbàn", meaning: "tổ chức" },
    { word: "举行", pinyin: "jǔxíng", meaning: "tiến hành, cử hành" },
    { word: "拒绝", pinyin: "jùjué", meaning: "từ chối" },
    { word: "距离", pinyin: "jùlí", meaning: "khoảng cách, cách" },
    { word: "聚会", pinyin: "jùhuì", meaning: "tụ tập, hội họp" },
    { word: "开玩笑", pinyin: "kāi wánxiào", meaning: "nói đùa, trêu chọc" },
    { word: "看法", pinyin: "kànfǎ", meaning: "quan điểm, cách nhìn" },
    { word: "考虑", pinyin: "kǎolǜ", meaning: "suy nghĩ, cân nhắc" },
    { word: "棵", pinyin: "kē", meaning: "cây (lượng từ cây cối)" },
    { word: "科学", pinyin: "kēxué", meaning: "khoa học" },
    { word: "咳嗽", pinyin: "késou", meaning: "ho" },
    { word: "可怜", pinyin: "kělián", meaning: "tội nghiệp, đáng thương" },
    { word: "可惜", pinyin: "kěxī", meaning: "đáng tiếc" },
    { word: "客厅", pinyin: "kètīng", meaning: "phòng khách" },
    { word: "肯定", pinyin: "kěndìng", meaning: "khẳng định, chắc chắn" },
    { word: "空", pinyin: "kōng", meaning: "trống rỗng, rảnh rỗi" },
    { word: "空气", pinyin: "kōngqì", meaning: "không khí" },
    { word: "恐龙", pinyin: "kǒnglóng", meaning: "khủng long" },
    { word: "苦", pinyin: "kǔ", meaning: "đắng, khổ" },
    { word: "酷", pinyin: "kù", meaning: "ngầu, ngầu lòi" },
    { word: "夸", pinyin: "kuā", meaning: "khen ngợi, ca ngợi" },
    { word: "宽", pinyin: "kuān", meaning: "rộng" },
    { word: "困", pinyin: "kùn", meaning: "buồn ngủ, vất vả" },
    { word: "困难", pinyin: "kùnnan", meaning: "khó khăn" },
    { word: "扩大", pinyin: "kuòdà", meaning: "mở rộng, khuếch đại" },
    { word: "拉", pinyin: "lā", meaning: "kéo, lôi" },
    { word: "垃圾桶", pinyin: "lājītǒng", meaning: "thùng rác" },
    { word: "辣", pinyin: "là", meaning: "cay" },
    { word: "来不及", pinyin: "láibují", meaning: "không kịp" },
    { word: "来得及", pinyin: "láidejí", meaning: "kịp lúc" },
    { word: "懒", pinyin: "lǎn", meaning: "lười biếng" },
    { word: "浪费", pinyin: "làngfèi", meaning: "lãng phí" },
    { word: "浪漫", pinyin: "làngmàn", meaning: "lãng mạn" },
    { word: "老虎", pinyin: "lǎohǔ", meaning: "con hổ, cọp" },
    { word: "冷静", pinyin: "lěngjìng", meaning: "bình tĩnh" },
    { word: "理发", pinyin: "lǐfà", meaning: "cắt tóc" },
    { word: "理解", pinyin: "lǐjiě", meaning: "thấu hiểu" },
    { word: "理想", pinyin: "lǐxiǎng", meaning: "lý tưởng" },
    { word: "礼貌", pinyin: "lǐmào", meaning: "lịch sự, lễ phép" },
    { word: "厉害", pinyin: "lìhai", meaning: "lợi hại, dữ dội" },
    { word: "力气", pinyin: "lìqi", meaning: "sức lực, sức mạnh" },
    { word: "例如", pinyin: "lìrú", meaning: "ví dụ như" },
    { word: "利润", pinyin: "lìrùn", meaning: "lợi nhuận" },
    { word: "利息", pinyin: "lìxī", meaning: "tiền lãi" },
    { word: "利益", pinyin: "lìyì", meaning: "lợi ích" },
    { word: "利用", pinyin: "lìyòng", meaning: "tận dụng, lợi dụng" },
    { word: "连", pinyin: "lián", meaning: "ngay cả, liên tiếp" },
    { word: "联系", pinyin: "liánxì", meaning: "liên hệ, liên lạc" },
    { word: "凉快", pinyin: "liángkuai", meaning: "mát mẻ" },
    { word: "零食", pinyin: "língshí", meaning: "đồ ăn vặt" },
    { word: "亮", pinyin: "liàng", meaning: "sáng, sáng sủa" },
    { word: "聊天", pinyin: "liáotiān", meaning: "trò chuyện, tán gẫu" },
    { word: "留", pinyin: "liú", meaning: "ở lại, lưu giữ" },
    { word: "流利", pinyin: "liúlì", meaning: "lưu loát, trôi chảy" },
    { word: "流行", pinyin: "liúxíng", meaning: "thịnh hành, phổ biến" },
    { word: "流泪", pinyin: "liúlèi", meaning: "chảy nước mắt" },
    { word: "乱", pinyin: "luàn", meaning: "lộn xộn, bừa bãi" },
    { word: "律师", pinyin: "lǜshī", meaning: "luật sư" },
    { word: "麻烦", pinyin: "máfan", meaning: "phiền phức, phiền hà" },
    { word: "马虎", pinyin: "mǎhu", meaning: "qua loa, ẩu tả" },
    { word: "满", pinyin: "mǎn", meaning: "đầy, trọn vẹn" },
    { word: "毛巾", pinyin: "máojīn", meaning: "khăn mặt" },
    { word: "美丽", pinyin: "měilì", meaning: "xinh đẹp" },
    { word: "梦", pinyin: "mèng", meaning: "giấc mơ, nằm mơ" },
    { word: "迷路", pinyin: "mílù", meaning: "lạc đường" },
    { word: "密码", pinyin: "mìmǎ", meaning: "mật khẩu" },
    { word: "免费", pinyin: "miǎnfèi", meaning: "miễn phí" },
    { word: "秒", pinyin: "miǎo", meaning: "giây (đơn vị thời gian)" },
    { word: "民族", pinyin: "mínzú", meaning: "dân tộc" },
    { word: "母亲", pinyin: "mǔqīn", meaning: "người mẹ" },
    { word: "目的", pinyin: "mùdì", meaning: "mục đích" },
    { word: "耐心", pinyin: "nàixīn", meaning: "kiên nhẫn, nhẫn nại" },
    { word: "难道", pinyin: "nándào", meaning: "lẽ nào, chẳng lẽ" },
    { word: "难受", pinyin: "nánshòu", meaning: "khó chịu, buồn bã" },
    { word: "内", pinyin: "nèi", meaning: "bên trong, nội bộ" },
    { word: "内容", pinyin: "nèiróng", meaning: "nội dung" },
    { word: "能力", pinyin: "nénglì", meaning: "năng lực, khả năng" },
    { word: "年龄", pinyin: "niánlíng", meaning: "tuổi tác" },
    { word: "弄", pinyin: "nòng", meaning: "làm, chế biến" },
    { word: "暖和", pinyin: "nuǎnhuo", meaning: "ấm áp" },
    { word: "偶尔", pinyin: "ǒu'ěr", meaning: "thỉnh thoảng, đôi khi" },
    { word: "排列", pinyin: "páiliè", meaning: "hàng lối, sắp xếp" },
    { word: "判断", pinyin: "pànduàn", meaning: "phán đoán, nhận định" },
    { word: "陪", pinyin: "péi", meaning: "đi cùng, đồng hành" },
    { word: "批评", pinyin: "pīpíng", meaning: "phê bình" },
    { word: "皮肤", pinyin: "pífū", meaning: "làn da" },
    { word: "脾气", pinyin: "píqi", meaning: "tính tình, tính khí" },
    { word: "篇", pinyin: "piān", meaning: "bài (văn, thơ, báo)" },
    { word: "乒乓球", pinyin: "pīngpāngqiú", meaning: "bóng bàn" },
    { word: "平时", pinyin: "píngshí", meaning: "ngày thường, lúc bình thường" },
    { word: "瓶子", pinyin: "píngzi", meaning: "cái chai, cái lọ" },
    { word: "破", pinyin: "pò", meaning: "vỡ, rách, hỏng" },
    { word: "葡萄", pinyin: "pútao", meaning: "quả nho" },
    { word: "普遍", pinyin: "pǔbiàn", meaning: "phổ biến" },
    { word: "其次", pinyin: "qícì", meaning: "tiếp theo, thứ hai" },
    { word: "其中", pinyin: "qízhōng", meaning: "trong đó" },
    { word: "气候", pinyin: "qìhòu", meaning: "khí hậu" },
    { word: "千万", pinyin: "qiānwàn", meaning: "nhất định, tuyệt đối" },
    { word: "签证", pinyin: "qiānzhèng", meaning: "thị thực, visa" },
    { word: "墙", pinyin: "qiáng", meaning: "bức tường" },
    { word: "敲", pinyin: "qiāo", meaning: "gõ, đập" },
    { word: "桥", pinyin: "qiáo", meaning: "cây cầu" },
    { word: "巧克力", pinyin: "qiǎokèlì", meaning: "sô-cô-la" },
    { word: "亲戚", pinyin: "qīnqi", meaning: "họ hàng, thân thích" },
    { word: "轻", pinyin: "qīng", meaning: "nhẹ" },
    { word: "轻松", pinyin: "qīngsōng", meaning: "thảnh thơi, thư thái" },
    { word: "情况", pinyin: "qíngkuàng", meaning: "tình hình" },
    { word: "请客", pinyin: "qǐngkè", meaning: "mời khách, đãi tiệc" },
    { word: "穷", pinyin: "qióng", meaning: "nghèo" },
    { word: "区别", pinyin: "qūbié", meaning: "khác biệt, phân biệt" },
    { word: "取", pinyin: "qǔ", meaning: "lấy, rút (tiền)" },
    { word: "全部", pinyin: "quánbù", meaning: "toàn bộ, tất cả" },
    { word: "缺点", pinyin: "quēdiǎn", meaning: "khuyết điểm, nhược điểm" },
    { word: "缺少", pinyin: "quēshǎo", meaning: "thiếu hụt" },
    { word: "却", pinyin: "què", meaning: "lại, nhưng lại" },
    { word: "确实", pinyin: "quèshí", meaning: "thực sự, quả thật" },
    { word: "群", pinyin: "qún", meaning: "bầy, đàn, nhóm" },
    { word: "热闹", pinyin: "rènao", meaning: "náo nhiệt, nhộn nhịp" },
    { word: "人民币", pinyin: "rénmínbì", meaning: "Nhân dân tệ" },
    { word: "任何", pinyin: "rènhé", meaning: "bất kỳ" },
    { word: "任务", pinyin: "rènwu", meaning: "nhiệm vụ" },
    { word: "扔", pinyin: "rēng", meaning: "ném, vứt" },
    { word: "仍然", pinyin: "réngrán", meaning: "vẫn, vẫn như cũ" },
    { word: "日记", pinyin: "rìjì", meaning: "nhật ký" },
    { word: "入口", pinyin: "rùkǒu", meaning: "lối vào" },
    { word: "散步", pinyin: "sànbù", meaning: "tản bộ, đi dạo" },
    { word: "森林", pinyin: "sēnlín", meaning: "rừng rậm" },
    { word: "沙发", pinyin: "shāfā", meaning: "ghế sofa" },
    { word: "伤心", pinyin: "shāngxīn", meaning: "đau lòng, thương tâm" },
    { word: "商量", pinyin: "shāngliang", meaning: "thương lượng, bàn bạc" },
    { word: "稍微", pinyin: "shāowēi", meaning: "hơi hơi, một chút" },
    { word: "社会", pinyin: "shèhuì", meaning: "xã hội" },
    { word: "深", pinyin: "shēn", meaning: "sâu, đậm (màu)" },
    { word: "申请", pinyin: "shēnqǐng", meaning: "xin, nộp đơn xin" },
    { word: "甚至", pinyin: "shènzhì", meaning: "thậm chí" },
    { word: "生活", pinyin: "shēnghuó", meaning: "cuộc sống, sinh hoạt" },
    { word: "生命", pinyin: "shēngmìng", meaning: "sinh mạng, sự sống" },
    { word: "生意", pinyin: "shēngyi", meaning: "buôn bán, kinh doanh" },
    { word: "省", pinyin: "shěng", meaning: "tỉnh thành; tiết kiệm" },
    { word: "剩", pinyin: "shèng", meaning: "dư thừa, còn lại" },
    { word: "失败", pinyin: "shībài", meaning: "thất bại" },
    { word: "失望", pinyin: "shīwàng", meaning: "thất vọng" },
    { word: "师傅", pinyin: "shīfu", meaning: "thợ, sư phụ" },
    { word: "湿润", pinyin: "shīrùn", meaning: "ẩm ướt, ẩm mịn" },
    { word: "狮子", pinyin: "shīzi", meaning: "con sư tử" },
    { word: "十分", pinyin: "shífēn", meaning: "vô cùng, vô cùng" },
    { word: "实际", pinyin: "shíjì", meaning: "thực tế" },
    { word: "食品", pinyin: "shípǐn", meaning: "thực phẩm, đồ ăn" },
    { word: "礼貌", pinyin: "lǐmào", meaning: "lễ phép" },
    { word: "适合", pinyin: "shìhé", meaning: "thích hợp, phù hợp" },
    { word: "适应", pinyin: "shìyìng", meaning: "thích nghi" },
    { word: "世纪", pinyin: "shìjì", meaning: "thế kỷ" },
    { word: "收", pinyin: "shōu", meaning: "thu, nhận" },
    { word: "收入", pinyin: "shōurù", meaning: "thu nhập" },
    { word: "收拾", pinyin: "shōushi", meaning: "dọn dẹp, thu dọn" },
    { word: "首都", pinyin: "shǒudū", meaning: "thủ đô" },
    { word: "首先", pinyin: "shǒuxiān", meaning: "đầu tiên, trước hết" },
    { word: "受不了", pinyin: "shòubuliǎo", meaning: "chịu không nổi" },
    { word: "受到", pinyin: "shòudào", meaning: "nhận được, bị" },
    { word: "售货员", pinyin: "shòuhuòyuán", meaning: "nhân viên bán hàng" },
    { word: "输", pinyin: "shū", meaning: "thua, thất bại" },
    { word: "熟悉", pinyin: "shúxī", meaning: "quen thuộc, am hiểu" },
    { word: "数量", pinyin: "shùliàng", meaning: "số lượng" },
    { word: "数字", pinyin: "shùzì", meaning: "con số, chữ số" },
    { word: "帅", pinyin: "shuài", meaning: "đẹp trai" },
    { word: "顺便", pinyin: "shùnbiàn", meaning: "nhân tiện, tiện thể" },
    { word: "顺利", pinyin: "shùnlì", meaning: "thuận lợi" },
    { word: "顺序", pinyin: "shùnxù", meaning: "thứ tự, tuần tự" },
    { word: "说明", pinyin: "shuōmíng", meaning: "thuyết minh, giải thích" },
    { word: "硕士", pinyin: "shuòshì", meaning: "thạc sĩ" },
    { word: "死", pinyin: "sǐ", meaning: "chết" },
    { word: "速度", pinyin: "sùdù", meaning: "tốc độ" },
    { word: "塑料袋", pinyin: "sùliàodài", meaning: "túi nilon" },
    { word: "酸", pinyin: "suān", meaning: "chua, mỏi (cơ)" },
    { word: "随便", pinyin: "suíbiàn", meaning: "tùy ý, tùy tiện" },
    { word: "随着", pinyin: "suízhe", meaning: "cùng với, đi kèm" },
    { word: "孙子", pinyin: "sūnzi", meaning: "cháu trai" },
    { word: "所有", pinyin: "suǒyǒu", meaning: "tất cả, toàn bộ" },
    { word: "台", pinyin: "tái", meaning: "đài, bệ, chiếc (lượng từ máy móc)" },
    { word: "抬", pinyin: "tái", meaning: "ngẩng, giơ, khiêng" },
    { word: "态度", pinyin: "tàidu", meaning: "thái độ" },
    { word: "弹钢琴", pinyin: "tán gāngqín", meaning: "đánh đàn piano" },
    { word: "谈", pinyin: "tán", meaning: "nói chuyện, đàm đạo" },
    { word: "汤", pinyin: "tāng", meaning: "canh, súp" },
    { word: "趟", pinyin: "tàng", meaning: "chuyến, lượt" },
    { word: "糖", pinyin: "táng", meaning: "đường, kẹo" },
    { word: "躺", pinyin: "tǎng", meaning: "nằm" },
    { word: "讨论", pinyin: "tǎolùn", meaning: "thảo luận" },
    { word: "讨厌", pinyin: "tǎoyàn", meaning: "ghét, đáng ghét" },
    { word: "特点", pinyin: "tèdiǎn", meaning: "đặc điểm" },
    { word: "提", pinyin: "tí", meaning: "xách, nhắc đến, đề xuất" },
    { word: "提供", pinyin: "tígōng", meaning: "cung cấp" },
    { word: "提前", pinyin: "tíqián", meaning: "làm trước, sớm hơn" },
    { word: "提醒", pinyin: "tíxǐng", meaning: "nhắc nhở" },
    { word: "填空", pinyin: "tiánkòng", meaning: "điền vào chỗ trống" },
    { word: "条件", pinyin: "tiáojiàn", meaning: "điều kiện" },
    { word: "停止", pinyin: "tíngzhǐ", meaning: "dừng lại, đình chỉ" },
    { word: "挺", pinyin: "tǐng", meaning: "rất, khá" },
    { word: "通过", pinyin: "tōngguò", meaning: "thông qua, vượt qua" },
    { word: "通知", pinyin: "tōngzhī", meaning: "thông báo" },
    { word: "同情", pinyin: "tóngqíng", meaning: "đồng cảm, thương hại" },
    { word: "推", pinyin: "tuī", meaning: "đẩy" },
    { word: "推迟", pinyin: "tuīchí", meaning: "hoãn lại, lùi lịch" },
    { word: "脱", pinyin: "tuō", meaning: "cởi (áo, giày)" },
    { word: "吐", pinyin: "tù", meaning: "nôn, mửa" },
    { word: "袜子", pinyin: "wàzi", meaning: "đôi tất, vớ" },
    { word: "完全", pinyin: "wánquán", meaning: "hoàn toàn" },
    { word: "网球", pinyin: "wǎngqiú", meaning: "quần vợt, tennis" },
    { word: "网站", pinyin: "wǎngzhàn", meaning: "trang web" },
    { word: "往", pinyin: "wǎng", meaning: "hướng về" },
    { word: "往往", pinyin: "wǎngwǎng", meaning: "thường hay (theo thói quen)" },
    { word: "效果", pinyin: "xiàoguǒ", meaning: "hiệu quả" },
    { word: "危险", pinyin: "wēixiǎn", meaning: "nguy hiểm" },
    { word: "卫生间", pinyin: "wèishēngjiān", meaning: "phòng vệ sinh" },
    { word: "味道", pinyin: "wèidào", meaning: "mùi vị" },
    { word: "温度", pinyin: "wēndù", meaning: "nhiệt độ" },
    { word: "文章", pinyin: "wénzhāng", meaning: "bài văn, bài báo" },
    { word: "污染", pinyin: "wūrǎn", meaning: "ô nhiễm" },
    { word: "无", pinyin: "wú", meaning: "không có, vô" },
    { word: "无聊", pinyin: "wúliáo", meaning: "chán ngắt, nhảm nhí" },
    { word: "无论", pinyin: "wúlùn", meaning: "bất luận, dù cho" },
    { word: "误会", pinyin: "wùhuì", meaning: "hiểu nhầm" },
    { word: "西红柿", pinyin: "xīhóngshì", meaning: "quả cà chua" },
    { word: "吸引", pinyin: "xīyǐn", meaning: "thu hút, hấp dẫn" },
    { word: "咸", pinyin: "xián", meaning: "mặn" },
    { word: "现金", pinyin: "xiànjīn", meaning: "tiền mặt" },
    { word: "羡慕", pinyin: "xiànmù", meaning: "ghen tị, ngưỡng mộ" },
    { word: "相反", pinyin: "xiāngfǎn", meaning: "trái ngược" },
    { word: "相同", pinyin: "xiāngtóng", meaning: "giống nhau" },
    { word: "香", pinyin: "xiāng", meaning: "thơm" },
    { word: "详细", pinyin: "xiángxì", meaning: "chi tiết, kỹ lưỡng" },
    { word: "响", pinyin: "xiǎng", meaning: "keo, vang lên" },
    { word: "橡皮", pinyin: "xiàngpí", meaning: "cục tẩy" },
    { word: "消息", pinyin: "xiāoxi", meaning: "tin tức, thông tin" },
    { word: "小吃", pinyin: "xiǎochī", meaning: "món ăn vặt" },
    { word: "小说", pinyin: "xiǎoshuō", meaning: "tiểu thuyết" },
    { word: "效果", pinyin: "xiàoguǒ", meaning: "kết quả, hiệu quả" },
    { word: "笑话", pinyin: "xiàohua", meaning: "trò cười, chuyện tếu" },
    { word: "心情", pinyin: "xīnqíng", meaning: "tâm trạng" },
    { word: "辛苦", pinyin: "xīnkǔ", meaning: "vất vả, cực khổ" },
    { word: "信封", pinyin: "xìnfēng", meaning: "phong bì thư" },
    { word: "信息", pinyin: "xìnxī", meaning: "thông tin, tin nhắn" },
    { word: "信心", pinyin: "xìnxīn", meaning: "lòng tin, sự tự tin" },
    { word: "兴奋", pinyin: "xīngfèn", meaning: "hào hứng, phấn khích" },
    { word: "行", pinyin: "xíng", meaning: "được, ok" },
    { word: "行动", pinyin: "xíngdòng", meaning: "hành động" },
    { word: "行人", pinyin: "xíngrén", meaning: "người đi bộ" },
    { word: "行为", pinyin: "xíngwéi", meaning: "hành vi" },
    { word: "醒", pinyin: "xǐng", meaning: "tỉnh giấc, tỉnh táo" },
    { word: "幸福", pinyin: "xìngfú", meaning: "hạnh phúc" },
    { word: "性格", pinyin: "xìnggé", meaning: "tính cách" },
    { word: "性别", pinyin: "xìngbié", meaning: "giới tính" },
    { word: "修理", pinyin: "xiūlǐ", meaning: "sửa chữa" },
    { word: "许多", pinyin: "xǔduō", meaning: "rất nhiều" },
    { word: "学期", pinyin: "xuéqī", meaning: "học kỳ" },
    { word: "压力", pinyin: "yālì", meaning: "áp lực" },
    { word: "牙膏", pinyin: "yágāo", meaning: "kem đánh răng" },
    { word: "亚洲", pinyin: "Yàzhōu", meaning: "Châu Á" },
    { word: "呀", pinyin: "ya", meaning: "chà, a (thán từ)" },
    { word: "严格", pinyin: "yángé", meaning: "nghiêm khắc, khắt khe" },
    { word: "严重", pinyin: "yánzhòng", meaning: "nghiêm trọng" },
    { word: "盐", pinyin: "yán", meaning: "muối" },
    { word: "研究", pinyin: "yánjiū", meaning: "nghiên cứu" },
    { word: "演出", pinyin: "yǎnchū", meaning: "biểu diễn" },
    { word: "演员", pinyin: "yǎnyuán", meaning: "diễn viên" },
    { word: "阳光", pinyin: "yángguāng", meaning: "ánh nắng mặt trời" },
    { word: "养", pinyin: "yǎng", meaning: "nuôi dưỡng, chăm sóc" },
    { word: "样子", pinyin: "yàngzi", meaning: "dáng vẻ, kiểu dáng" },
    { word: "邀请", pinyin: "yāoqǐng", meaning: "mời" },
    { word: "钥匙", pinyin: "yàoshi", meaning: "chìa khóa" },
    { word: "也许", pinyin: "yěxǔ", meaning: "có lẽ, có thể" },
    { word: "叶子", pinyin: "yèzi", meaning: "lá cây" },
    { word: "页", pinyin: "yè", meaning: "trang (sách)" },
    { word: "一切", pinyin: "yíqiè", meaning: "tất cả, toàn bộ" },
    { word: "以", pinyin: "yǐ", meaning: "dùng, bằng, lấy" },
    { word: "以为", pinyin: "yǐwéi", meaning: "tưởng rằng (thường sai)" },
    { word: "艺术", pinyin: "yìshù", meaning: "nghệ thuật" },
    { word: "意见", pinyin: "yìjiàn", meaning: "ý kiến" },
    { word: "意义", pinyin: "yìyì", meaning: "ý nghĩa" },
    { word: "因此", pinyin: "yīncǐ", meaning: "do đó, vì vậy" },
    { word: "赢", pinyin: "yíng", meaning: "thắng, chiến thắng" },
    { word: "印象", pinyin: "yìnxiàng", meaning: "ấn tượng" },
    { word: "勇敢", pinyin: "yǒnggǎn", meaning: "dũng cảm" },
    { word: "永远", pinyin: "yǒngyuǎn", meaning: "vĩnh viễn, mãi mãi" },
    { word: "优点", pinyin: "yōudiǎn", meaning: "ưu điểm" },
    { word: "幽默", pinyin: "yōumò", meaning: "hài hước" },
    { word: "由", pinyin: "yóu", meaning: "do, bởi" },
    { word: "由于", pinyin: "yóuyú", meaning: "do, bởi vì" },
    { word: "邮局", pinyin: "yóujú", meaning: "bưu điện" },
    { word: "友好", pinyin: "yǒuhǎo", meaning: "thân thiện, hữu nghị" },
    { word: "友谊", pinyin: "yǒuyì", meaning: "tình bạn, hữu nghị" },
    { word: "有趣", pinyin: "yǒuqù", meaning: "thú vị" },
    { word: "于是", pinyin: "yúshì", meaning: "thế là, cho nên" },
    { word: "愉快", pinyin: "yúkuài", meaning: "vui vẻ, sảng khoái" },
    { word: "与", pinyin: "yǔ", meaning: "và, với" },
    { word: "羽毛球", pinyin: "yǔmáoqiú", meaning: "cầu lông" },
    { word: "语法", pinyin: "yǔfǎ", meaning: "ngữ pháp" },
    { word: "语言", pinyin: "yǔyán", meaning: "ngôn ngữ" },
    { word: "预习", pinyin: "yùxí", meaning: "chuẩn bị bài trước" },
    { word: "圆", pinyin: "yuán", meaning: "tròn" },
    { word: "原谅", pinyin: "yuánliàng", meaning: "tha thứ, thứ lỗi" },
    { word: "原因", pinyin: "yuányīn", meaning: "nguyên nhân" },
    { word: "约会", pinyin: "yuēhuì", meaning: "hẹn hò" },
    { word: "阅读", pinyin: "yuèdú", meaning: "đọc hiểu" },
    { word: "云", pinyin: "yún", meaning: "mây" },
    { word: "允许", pinyin: "yǔnxǔ", meaning: "cho phép" },
    { word: "杂志", pinyin: "zázhì", meaning: "tạp chí" },
    { word: "咱们", pinyin: "zánmen", meaning: "chúng ta (bao gồm người nghe)" },
    { word: "暂时", pinyin: "zànshí", meaning: "tạm thời" },
    { word: "赞成", pinyin: "zànchéng", meaning: "tán thành, ủng hộ" },
    { word: "脏", pinyin: "zāng", meaning: "bẩn, dơ" },
    { word: "责任", pinyin: "zérèn", meaning: "trách nhiệm" },
    { word: "增加", pinyin: "zēngjiā", meaning: "tăng thêm" },
    { word: "占线", pinyin: "zhànxiàn", meaning: "bận máy (điện thoại)" },
    { word: "招聘", pinyin: "zhāopìn", meaning: "tuyển dụng" },
    { word: "照", pinyin: "zhào", meaning: "chiếu, chụp ảnh" },
    { word: "真正", pinyin: "zhēnzhèng", meaning: "chân chính, đích thực" },
    { word: "整理", pinyin: "zhěnglǐ", meaning: "sắp xếp, thu dọn" },
    { word: "正常", pinyin: "zhèngcháng", meaning: "bình thường" },
    { word: "正好", pinyin: "zhènghǎo", meaning: "vừa hay, vừa vặn" },
    { word: "正确", pinyin: "zhèngquè", meaning: "chính xác, đúng" },
    { word: "正式", pinyin: "zhèngshì", meaning: "chính thức" },
    { word: "证明", pinyin: "zhèngmíng", meaning: "chứng minh" },
    { word: "之", pinyin: "zhī", meaning: "của (trợ từ hán văn)" },
    { word: "支持", pinyin: "zhīchí", meaning: "ủng hộ, hỗ trợ" },
    { word: "知识", pinyin: "zhīshi", meaning: "kiến thức, hiểu biết" },
    { word: "直接", pinyin: "zhíjiē", meaning: "trực tiếp" },
    { word: "值得", pinyin: "zhíde", meaning: "xứng đáng" },
    { word: "职业", pinyin: "zhíyè", meaning: "nghề nghiệp" },
    { word: "植物", pinyin: "zhíwù", meaning: "thực vật, cây cỏ" },
    { word: "只要", pinyin: "zhǐyào", meaning: "chỉ cần" },
    { word: "指", pinyin: "zhǐ", meaning: "chỉ trỏ, ngón tay" },
    { word: "至少", pinyin: "zhìshǎo", meaning: "ít nhất" },
    { word: "质量", pinyin: "zhìliàng", meaning: "chất lượng" },
    { word: "重", pinyin: "zhòng", meaning: "nặng" },
    { word: "重点", pinyin: "zhòngdiǎn", meaning: "trọng tâm, điểm chính" },
    { word: "重视", pinyin: "zhòngshì", meaning: "coi trọng, xem trọng" },
    { word: "周围", pinyin: "zhōuwéi", meaning: "xung quanh" },
    { word: "猪", pinyin: "zhū", meaning: "con heo, con lợn" },
    { word: "逐渐", pinyin: "zhújiàn", meaning: "dần dần, từng bước" },
    { word: "主动", pinyin: "zhǔdòng", meaning: "chủ động" },
    { word: "主意", pinyin: "zhǔyi", meaning: "ý kiến, chủ ý" },
    { word: "祝贺", pinyin: "zhùhè", meaning: "chúc mừng" },
    { word: "著名", pinyin: "zhùmíng", meaning: "nổi tiếng, lừng danh" },
    { word: "专门", pinyin: "zhuānmén", meaning: "chuyên môn, đặc biệt" },
    { word: "专业", pinyin: "zhuānyè", meaning: "chuyên ngành" },
    { word: "赚", pinyin: "zhuàn", meaning: "kiếm (tiền), lời" },
    { word: "撞", pinyin: "zhuàng", meaning: "va, đụng, tông" },
    { word: "准确", pinyin: "zhǔnquè", meaning: "chuẩn xác" },
    { word: "准时", pinyin: "zhǔnshí", meaning: "đúng giờ" },
    { word: "仔细", pinyin: "zǐxì", meaning: "kỹ lưỡng, tỉ mỉ" },
    { word: "自然", pinyin: "zìrán", meaning: "tự nhiên, thiên nhiên" },
    { word: "自信", pinyin: "zìxìn", meaning: "tự tin" },
    { word: "总结", pinyin: "zǒngjié", meaning: "tổng kết" },
    { word: "租", pinyin: "zū", meaning: "thuê, mướn" },
    { word: "最好", pinyin: "zuìhǎo", meaning: "tốt nhất, nên" },
    { word: "尊重", pinyin: "zūnzhòng", meaning: "tôn trọng" },
    { word: "左右", pinyin: "zuǒyòu", meaning: "khoảng chừng, trái phải" },
    { word: "作家", pinyin: "zuòjiā", meaning: "nhà văn" },
    { word: "作用", pinyin: "zuòyòng", meaning: "tác dụng, vai trò" },
    { word: "作者", pinyin: "zuòzhě", meaning: "tác giả" },
    { word: "座", pinyin: "zuò", meaning: "tòa, ngọn, chỗ ngồi" },
    { word: "座位", pinyin: "zuòwèi", meaning: "chỗ ngồi" }
];
async function loadLocalHSK5() {
  const response = await fetch('hsk5.json');
  const hsk5Data = await response.json();
  
  hskData[5] = hsk5Data;
}

loadLocalHSK5();

let currentLevel = "1";
let currentWordIndex = 0;
let typingWordList = [];
let currentCommFilter = "all";

// Khởi tạo ứng dụng
document.addEventListener('DOMContentLoaded', () => {
    document.getElementById('hsk-level').addEventListener('change', (e) => {
        currentLevel = e.target.value;
        renderList();
        initTyping();
        renderCommunication();
    });
    
    document.getElementById('typing-input').addEventListener('keypress', function(e) {
        if (e.key === 'Enter') {
            checkTyping();
        }
    });

    renderList();
    initTyping();
    renderCommunication();
});

// Chuyển Tab
function switchMode(mode) {
    document.querySelectorAll('section').forEach(sec => sec.classList.remove('active'));
    document.getElementById(`${mode}-mode`).classList.add('active');
    
    if (mode === 'typing') initTyping();
    if (mode === 'communication') renderCommunication();
}

// Render Danh sách từ
function renderList() {
    const list = hskData[currentLevel] || [];
    const container = document.getElementById('word-list');
    document.getElementById('total-words').textContent = list.length;
    
    container.innerHTML = list.map(item => `
        <div class="word-card">
            <div class="hanzi">${item.word}</div>
            <div class="pinyin">${item.pinyin}</div>
            <div class="meaning">${item.meaning}</div>
        </div>
    `).join('');
}

// Khởi tạo bài tập gõ
function initTyping() {
    typingWordList = [...(hskData[currentLevel] || [])];
    typingWordList.sort(() => Math.random() - 0.5); 
    currentWordIndex = 0;
    showTypingWord();
}

function showTypingWord() {
    const feedback = document.getElementById('typing-feedback');
    const nextBtn = document.getElementById('next-word-btn');
    const input = document.getElementById('typing-input');

    if (typingWordList.length === 0) {
        document.getElementById('typing-word').textContent = "Trống";
        document.getElementById('typing-meaning').textContent = "Chưa có dữ liệu cho cấp độ này";
        input.disabled = true;
        return;
    }

    if (currentWordIndex >= typingWordList.length) {
        document.getElementById('typing-word').textContent = "🎉";
        document.getElementById('typing-meaning').textContent = "Bạn đã hoàn thành cấp độ này!";
        input.disabled = true;
        return;
    }

    const currentItem = typingWordList[currentWordIndex];
    document.getElementById('typing-word').textContent = currentItem.word;
    document.getElementById('typing-meaning').textContent = currentItem.meaning;
    
    input.value = "";
    input.disabled = false;
    input.focus();
    feedback.textContent = "";
    nextBtn.classList.add('hidden');
}

function checkTyping() {
    if (currentWordIndex >= typingWordList.length) return;

    const inputVal = document.getElementById('typing-input').value.trim().toLowerCase();
    const currentItem = typingWordList[currentWordIndex];
    
    const cleanPinyin = currentItem.pinyin.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

    const isMatch = (inputVal === cleanPinyin) || 
                    (inputVal === currentItem.pinyin.toLowerCase()) || 
                    (inputVal === currentItem.word); 

    const feedback = document.getElementById('typing-feedback');
    const nextBtn = document.getElementById('next-word-btn');

    if (isMatch) {
        feedback.textContent = "✅ Chính xác!";
        feedback.className = "correct";
        document.getElementById('typing-input').disabled = true;
        nextBtn.classList.remove('hidden');
        nextBtn.focus();
    } else {
        feedback.textContent = "❌ Sai rồi, thử lại nhé!";
        feedback.className = "incorrect";
    }
}

function nextTypingWord() {
    currentWordIndex++;
    showTypingWord();
}

// ----------------------------------------------------
// Chức năng Luyện giao tiếp
// ----------------------------------------------------

function filterDifficulty(level) {
    currentCommFilter = level;
    document.querySelectorAll('.filter-btn').forEach(btn => btn.classList.remove('active'));
    event.target.classList.add('active');
    renderCommunication();
}

function renderCommunication() {
    const rawList = communicationData[currentLevel] || [];
    const container = document.getElementById('comm-list');

    let filteredList = rawList;
    if (currentCommFilter !== 'all') {
        filteredList = rawList.filter(item => item.difficulty === currentCommFilter);
    }

    if (filteredList.length === 0) {
        container.innerHTML = `<p style="text-align:center; color:#888;">Chưa có câu hỏi giao tiếp nào cho cấp độ hoặc bộ lọc này.</p>`;
        return;
    }

    container.innerHTML = filteredList.map((item, index) => {
        let badgeClass = "badge-easy";
        if (item.difficulty === "Trung bình") badgeClass = "badge-medium";
        if (item.difficulty === "Khó") badgeClass = "badge-hard";

        return `
            <div class="comm-card">
                <div class="comm-header">
                    <span class="badge ${badgeClass}">${item.difficulty}</span>
                    <button class="toggle-answer-btn" onclick="toggleAnswer(${index})">💡 Mẫu trả lời</button>
                </div>
                <div class="question-box">
                    <div class="q-hanzi">❓ ${item.question}</div>
                    <div class="q-pinyin">📌 Pinyin: ${item.pinyin}</div>
                    <div class="q-meaning">💬 Dịch: ${item.meaning}</div>
                </div>
                <div class="answer-box hidden" id="answer-${index}">
                    <div class="a-hanzi">🗣️ ${item.answer}</div>
                    <div class="q-pinyin">📌 Pinyin: ${item.answerPinyin}</div>
                    <div class="q-meaning">💬 Dịch: ${item.answerMeaning}</div>
                </div>
            </div>
        `;
    }).join('');
}

function toggleAnswer(index) {
    const answerBox = document.getElementById(`answer-${index}`);
    answerBox.classList.toggle('hidden');
}
// ==========================================
// BỔ SUNG: TÌM KIẾM TỪ VỰNG & BỎ QUA BÀI GÕ
// ==========================================

// 1. Hàm tìm kiếm từ vựng
function searchWords() {
    const keyword = document.getElementById('search-input').value.toLowerCase().trim();
    const currentLevel = document.getElementById('hsk-level').value;
    
    // Lấy danh sách từ của cấp độ hiện tại (thay hskData bằng tên biến chứa dữ liệu của bạn)
    const currentVocabList = hskData[currentLevel] || [];

    const filteredList = currentVocabList.filter(item => 
        item.word.includes(keyword) || 
        (item.pinyin && item.pinyin.toLowerCase().includes(keyword)) || 
        (item.meaning && item.meaning.toLowerCase().includes(keyword))
    );

    // Gọi lại hàm hiển thị danh sách từ của bạn với danh sách đã lọc
    renderWordList(filteredList); 
}

// 2. Hàm bỏ qua từ trong bài tập gõ
function skipTypingWord() {
    const feedbackEl = document.getElementById('typing-feedback');

    // Lấy từ hiện tại đang hiển thị (thay currentTypingWord bằng biến từ hiện tại của bạn)
    if (typeof currentTypingWord !== 'undefined' && currentTypingWord) {
        feedbackEl.style.color = '#e67e22';
        feedbackEl.innerText = `⏭️ Đã bỏ qua. Đáp án: "${currentTypingWord.word}" (${currentTypingWord.pinyin})`;
        
        setTimeout(() => {
            feedbackEl.innerText = '';
            nextTypingWord(); // Gọi hàm chuyển từ tiếp theo sẵn có của bạn
        }, 1200);
    } else {
        nextTypingWord();
    }
}
// Hàm đọc từ tiếng Trung bằng giọng đọc chuẩn (zh-CN)
function speakWord(text) {
    if ('speechSynthesis' in window) {
        window.speechSynthesis.cancel(); // Dừng câu đọc trước đó nếu đang đọc
        const utterance = new SpeechSynthesisUtterance(text);
        utterance.lang = 'zh-CN'; // Ngôn ngữ Tiếng Trung
        utterance.rate = 0.80;    // Tốc độ đọc vừa phải
        window.speechSynthesis.speak(utterance);
    } else {
        alert("Trình duyệt của bạn không hỗ trợ phát âm!");
    }
}

// Hàm phát âm từ đang xuất hiện ở phần bài tập gõ
function speakCurrentTypingWord() {
    const wordElement = document.getElementById('typing-word');
    if (wordElement && wordElement.innerText) {
        speakWord(wordElement.innerText);
    }
}
